import React, { FC } from 'react';
import { Anchor, Space, Stack, Title, Text, Code } from '@mantine/core';
import styles from '../DocMgtDocumentation.module.css';
import { CLIENT_DASHBOARD } from 'constants/routes';
import { Link } from 'react-router-dom';

const Webhook: FC = () => {
  return (
    <>
      <Title id="webhook" order={4}>
        3. Webhook
      </Title>
      <Space h="md" />
      <div className={styles.subContent}>
        <Stack gap="sm">
          <Text>
            When a webhook is created, users provide an <strong>API key</strong>{' '}
            and a <strong>Secret key</strong>. The <code>api-key</code> is sent
            in the request headers, and the <code>secret key</code> is used to
            generate a HMAC signature. You can manage your webhooks under the{' '}
            <Anchor component={Link} to={CLIENT_DASHBOARD.DOC_MGT_WEBHOOKS}>
              Webhooks
            </Anchor>{' '}
            section
          </Text>

          <Text>For example, given the following webhook request body:</Text>
          <Code block>
            {`{
  "requestId": "string",
  "hmacSignature": "string",
  "data": {
    "companyName": "ABC ENTERPRISE",
    "registrationNumber": "16888888A",
    "address": "123 ABC ROAD"
  },
  "payload": {
    "refId": "string",
    "documentType": "string",
    "templateId": "string",
    "fileName": "string"
  }
}`}
          </Code>

          <Text>
            The HMAC signature is generated by concatenating the{' '}
            <code>data</code> object in key-value order like this:
          </Text>
          <Code block>
            companyName:ABC ENTERPRISE:registrationNumber:16888888A:address:123
            ABC ROAD
          </Code>
          <Text>
            The resulting string is passed through the <code>SHA256</code>{' '}
            algorithm with the secret key to produce the{' '}
            <code>hmacSignature</code>.
          </Text>

          <Text>
            The receiving service can choose to authenticate the webhook using
            the <code>api-key</code> in the header or validate the integrity
            using the <code>hmacSignature</code> in the body.
          </Text>

          <Title id="consensus-messaging-webhook" order={5}>
            3.1 Consensus Messaging Webhook Example:
          </Title>
          <div className={styles.subContent}>
            <Code block>
              {`{
  "requestId": "string",
  "hmacSignature": "string",
  "data": {
    "topicId": "string",
    "transactionId": "string",
    "url": "string"
  },
  "payload": {
    "refId": "string",
    "eventName": "string"
  }
}`}
            </Code>
          </div>

          <Title id="document-extraction-webhook" order={5}>
            3.2 Document Extraction Webhook Example:
          </Title>
          <div className={styles.subContent}>
            <Code block>
              {`{
  "requestId": "string",
  "hmacSignature": "string",
  "data": {
    "invoiceNumber": "TEST-123",
    "date": "04-09-2023",
    "items": [
      {
        "item": "BP1",
        "quantity": 206,
        "unitPrice": 229,
        "totalInvoice": 47174
      },
      {
        "item": "BP2",
        "quantity": 41,
        "unitPrice": 264,
        "totalInvoice": 10824
      },
      {
        "item": "BP3",
        "quantity": 366,
        "unitPrice": 130,
        "totalInvoice": 47580
      }
    ]
  },
  "payload": {
    "refId": "string",
    "documentType": "string",
    "templateId": "string",
    "fileName": "string"
  }
}`}
            </Code>
            <Space h="md" />

            <Text fw={500}>Extraction Response Prompt Template:</Text>
            <Text size="sm">
              The extraction response is based on the following prompt
              definition:
            </Text>
            <Code block>
              {`[
  {
    "keyToExtract":"invoiceNumber",
    "format":"string",
    "description":"The invoice number"
  },
  {
    "keyToExtract":"date",
    "format":"string",
    "description":"The date of invoice in DD-MM-YYYY format"
  },
  {
    "keyToExtract":"items",
    "format":"array",
    "description":"Provide a detailed list of all line items on this invoice, including the following information for each item in these exact keys: item (this can be item code, upc, or item number for example), quantity, unitPrice (without currency), totalInvoice (total invoice for the item)."
  },
  {
    "keyToExtract":"tax",
    "format":"number",
    "description":"The total tax amount"
  }
]`}
            </Code>
          </div>
        </Stack>
      </div>
    </>
  );
};

export default Webhook;
