version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 315466746226.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - docker build -t spv -f Dockerfile .
      - docker tag spv:latest 315466746226.dkr.ecr.ap-southeast-1.amazonaws.com/spv:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 315466746226.dkr.ecr.ap-southeast-1.amazonaws.com/spv:latest