# SonarQube server URL
sonar.host.url=http://10.0.26.178:9000

# Project key
sonar.projectKey=funded-dev-project

# Project name
sonar.projectName=funded-dev-project

# Authentication token
sonar.login=sqp_e8644814c5b3c73928b2e53dcb7e9d934e341ebe

# Project version
sonar.projectVersion=1.0

# Source code directory
sonar.sources=.

# Coverage exclusions
sonar.coverage.exclusions=node_modules/,app.js,package.json,.scannerwork,.env,public/,db/,test/

