apiVersion: v1
kind: Service
metadata:
  name: trade-directory-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: trade-directory
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: metrics
      port: 5000
      targetPort: 5000
