// Lifecycle statuses grow as redesign phases land (extraction, validation,
// reconciliation) — stored as varchar, not a Postgres enum, so adding values
// needs no ALTER TYPE.
export enum DocumentStatusEnum {
  UPLOADED = 'UPLOADED',
  EXTRACTING = 'EXTRACTING',
  EXTRACTED = 'EXTRACTED',
  EXTRACTION_FAILED = 'EXTRACTION_FAILED',
  VALIDATED = 'VALIDATED',
  DISCREPANCY_FLAGGED = 'DISCREPANCY_FLAGGED',
  // Invoice failed the arithmetic gate — Finance Analyst reconciliation queue.
  INVOICE_MISMATCH = 'INVOICE_MISMATCH',
  ARCHIVED = 'ARCHIVED',
}

export enum DocumentEventTypeEnum {
  UPLOADED = 'UPLOADED',
  PRESIGNED_URL_ISSUED = 'PRESIGNED_URL_ISSUED',
  EXTRACTION_STARTED = 'EXTRACTION_STARTED',
  EXTRACTION_COMPLETED = 'EXTRACTION_COMPLETED',
  EXTRACTION_FAILED = 'EXTRACTION_FAILED',
  VALIDATION_COMPLETED = 'VALIDATION_COMPLETED',
  DISCREPANCY_FLAGGED = 'DISCREPANCY_FLAGGED',
  DISCREPANCY_CLEARED = 'DISCREPANCY_CLEARED',
  INVOICE_MATH_PASSED = 'INVOICE_MATH_PASSED',
  INVOICE_MATH_MISMATCH = 'INVOICE_MATH_MISMATCH',
  INVOICE_RECONCILED = 'INVOICE_RECONCILED',
  INVOICE_SUBMITTED = 'INVOICE_SUBMITTED',
  ARCHIVED = 'ARCHIVED',
}

export enum ExtractionMethodEnum {
  MARKITDOWN = 'markitdown',
  VISION_LLM = 'vision_llm',
}
