apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-management
  template:
    metadata:
      labels:
        app: document-management
    spec:
      containers:
        - image: 270075630987.dkr.ecr.ap-southeast-1.amazonaws.com/document-management:latest
          name: document-management
          ports:
            - containerPort: 3000
            - containerPort: 5000
          env:
            - name: ROOT_DIR
              value: '/usr/src/app/document-management'
            - name: PORT
              value: '3000'
            - name: KAFKA_BROKER_SSL
              value: 'false'
            - name: KAFKA_BROKERS
              value: 'b-1.synliansqfprodmsk.fauaoq.c4.kafka.ap-southeast-1.amazonaws.com:9092,b-2.synliansqfprodmsk.fauaoq.c4.kafka.ap-southeast-1.amazonaws.com:9092,b-3.synliansqfprodmsk.fauaoq.c4.kafka.ap-southeast-1.amazonaws.com:9092'
            - name: FRONTEND_DOMAIN
              value: 'https://portal.sqf.ai'
            - name: DOCUMENT_MANAGEMENT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: document-management-secret-key
                  key: secret-key
            - name: POSTGRES_HOST
              value: 'sqfprod.cluster-cpwyyusiswsi.ap-southeast-1.rds.amazonaws.com'
            - name: POSTGRES_PORT
              value: '5432'
            - name: POSTGRES_DATABASE
              value: 'document-management'
            - name: POSTGRES_USERNAME
              value: 'sqfprodadmin'
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-document-management
                  key: password
            - name: POSTGRES_SYNCHRONIZE
              value: 'true'
            - name: NODE_ENV
              value: 'production'
            - name: HEDERA_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: hedera-account-id
                  key: id
            - name: HEDERA_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: hedera-private-key
                  key: key
            - name: DEEP_SEEK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: deep-seek-api-key
                  key: key
            - name: DEEP_SEEK_URL
              value: 'https://api.deepseek.com'
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-s3
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-s3
                  key: secret-access-key
            - name: AWS_S3_REGION
              value: 'ap-southeast-1'
            - name: DOCUMENT_EXTRACTION_BUCKET_NAME
              value: 'prod-document-extraction.sqf.ai'
