export enum ApplicationStatusEnum {
  DRAFT = 'DRAFT',
  PENDING_EXPERIAN_CONSENT = 'PENDING_EXPERIAN_CONSENT',
  PENDING_EXPERIAN_REPORT = 'PENDING_EXPERIAN_REPORT',
  PENDING_CLIENT_SUBMISSION = 'PENDING_CLIENT_SUBMISSION',
  PENDING_ASSIGNEE_REVIEW = 'PENDING_ASSIGNEE_REVIEW',
  PENDING_RISK_FILTER_1 = 'PENDING_RISK_FILTER_1',
  PENDING_RISK_FILTER_2 = 'PENDING_RISK_FILTER_2',
}
