export enum ApplicationStatusEnum {
  DRAFT = 'DRAFT',
  PENDING_KYC_CONSENT = 'PENDING_KYC_CONSENT',
  PENDING_KYC_REPORT = 'PENDING_KYC_REPORT',
  PENDING_CLIENT_SUBMISSION = 'PENDING_CLIENT_SUBMISSION',
  PENDING_ASSIGNEE_REVIEW = 'PENDING_ASSIGNEE_REVIEW',
  PENDING_RISK_FILTER_1 = 'PENDING_RISK_FILTER_1',
  PENDING_RISK_FILTER_2 = 'PENDING_RISK_FILTER_2',
  // Customer Portal web intake (pass 1, 2026-07-24) — add-only values:
  // DRAFT -> SUBMITTED -> SCORED_PASS | SCORED_FAIL -> IN_CRC_REVIEW /
  // CLOSED_ARCHIVED (RM 10-working-day engagement window on FAIL).
  SUBMITTED = 'SUBMITTED',
  SCORED_PASS = 'SCORED_PASS',
  SCORED_FAIL = 'SCORED_FAIL',
  IN_CRC_REVIEW = 'IN_CRC_REVIEW',
  CLOSED_ARCHIVED = 'CLOSED_ARCHIVED',
}
