export enum ClientAwarderContractTypeEnum {
  SUPPLY = 'SUPPLY',
  SERVICES = 'SERVICES',
  SUPPLY_AND_SERVICES = 'SUPPLY_AND_SERVICES',
  OTHERS = 'OTHERS',
  // RETAIL = 'RETAIL',
  // WHOLESALE = 'WHOLESALE',
}
