export enum FacilityTypeEnum {
  PRE_FACTORING = 'PRE_FACTORING',
  TERM_FINANCING = 'TERM_FINANCING',
  POST_FACTORING = 'POST_FACTORING',
  BANK_GUARANTEE = 'BANK_GUARANTEE',
  SALARY_ADVANCE = 'SALARY_ADVANCE',
}
