export enum RiskFactorScoreMethodEnum {
  NUMERIC_SCORING = 'NUMERIC_SCORING',
  LABEL_SELECTION = 'LABEL_SELECTION',
  COUNTRY_SELECTION = 'COUNTRY_SELECTION',
  DROPDOWN_SELECTION = 'DROPDOWN_SELECTION',
}
