apiVersion: v1
kind: Service
metadata:
  name: customer-relationship-management-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: customer-relationship-management
  ports:
    - name: http
      port: 3000
      targetPort: 3000
    - name: metrics
      port: 5000
      targetPort: 5000
