export enum DependencyInjectionTokenEnum {
  TRADE_DIRECTORY_GRPC_CLIENT = 'TRADE_DIRECTORY_GRPC_CLIENT',
  RISK_OPERATION_GRPC_CLIENT = 'RISK_OPERATION_GRPC_CLIENT',
  AWS_S3_CLIENT = 'AWS_S3_CLIENT',
  EMAIL_TRANSPORTER = 'EMAIL_TRANSPORTER',
  DEFAULT_XML_BUILDER = 'DEFAULT_XML_BUILDER',
  DEFAULT_XML_PARSER = 'DEFAULT_XML_PARSER',
  CI_XML_PARSER = 'CI_XML_PARSER',
  BI_XML_PARSER = 'BI_XML_PARSER',
  KAFKA_PRODUCER = 'KAFKA_PRODUCER',
}
