upstream trade-directory {
  server trade-directory-service:3000;
}

upstream risk-operation {
  server risk-operation-service:3000;
}

upstream customer-relationship-management {
  server customer-relationship-management-service:3000;
}

upstream document-management {
  server document-management-service:3000;
}

upstream notification {
  server notification-service:3000;
}

server {
  listen 80;

  client_max_body_size 100m;

  location /trade-directory {
    proxy_pass http://trade-directory;
  }

  location /risk-operation {
    proxy_pass http://risk-operation;
  }

  location /customer-relationship-management {
    proxy_pass http://customer-relationship-management;
  }

  location /document-management {
    proxy_pass http://document-management;
  }

  location /notification {
    proxy_pass http://notification;
  }
}