export enum BankAccountTypeEnum {
  CURRENT_ACCOUNT = 'CURRENT_ACCOUNT',
  SAVINGS_ACCOUNT = 'SAVINGS_ACCOUNT',
  MULTI_CURRENCY_ACCOUNT = 'MULTI_CURRENCY_ACCOUNT',
  FIXED_DEPOSIT_ACCOUNT = 'FIXED_DEPOSIT_ACCOUNT',
}
