export enum ExperianReportTypeEnum {
  COMPANY_INTELLIGENCE = 'COMPANY_INTELLIGENCE',
  ENHANCED_COMPANY_INTELLIGENCE = 'ENHANCED_COMPANY_INTELLIGENCE',
  BUSINESS_INTELLIGENCE = 'BUSINESS_INTELLIGENCE',
  ENHANCED_BUSINESS_INTELLIGENCE = 'ENHANCED_BUSINESS_INTELLIGENCE',
  C_RISK_SCORE_INTELLIGENCE = 'C_RISK_SCORE_INTELLIGENCE',
  ENHANCED_C_RISK_SCORE_INTELLIGENCE = 'ENHANCED_C_RISK_SCORE_INTELLIGENCE',
}

export namespace ExperianReportTypeEnumHelper {
  export function CompanyIntelligence() {
    return [
      ExperianReportTypeEnum.COMPANY_INTELLIGENCE,
      ExperianReportTypeEnum.ENHANCED_COMPANY_INTELLIGENCE,
    ];
  }

  export function BusinessIntelligence() {
    return [
      ExperianReportTypeEnum.BUSINESS_INTELLIGENCE,
      ExperianReportTypeEnum.ENHANCED_BUSINESS_INTELLIGENCE,
    ];
  }
}
