export enum KycReportTypeEnum {
  COMPANY_INTELLIGENCE = 'COMPANY_INTELLIGENCE',
  ENHANCED_COMPANY_INTELLIGENCE = 'ENHANCED_COMPANY_INTELLIGENCE',
  BUSINESS_INTELLIGENCE = 'BUSINESS_INTELLIGENCE',
  ENHANCED_BUSINESS_INTELLIGENCE = 'ENHANCED_BUSINESS_INTELLIGENCE',
  C_RISK_SCORE_INTELLIGENCE = 'C_RISK_SCORE_INTELLIGENCE',
  ENHANCED_C_RISK_SCORE_INTELLIGENCE = 'ENHANCED_C_RISK_SCORE_INTELLIGENCE',
}

export namespace KycReportTypeEnumHelper {
  export function CompanyIntelligence() {
    return [
      KycReportTypeEnum.COMPANY_INTELLIGENCE,
      KycReportTypeEnum.ENHANCED_COMPANY_INTELLIGENCE,
    ];
  }

  export function BusinessIntelligence() {
    return [
      KycReportTypeEnum.BUSINESS_INTELLIGENCE,
      KycReportTypeEnum.ENHANCED_BUSINESS_INTELLIGENCE,
    ];
  }
}
