export enum OrganizationPersonRoleEnum {
  SQFSYS = 'SQFSYS',
  SUPERUSER = 'SUPERUSER',
  CEO = 'CEO',
  COO = 'COO',
  CLIENT_COVERAGE = 'CLIENT_COVERAGE',
  CUSTOMER_SUCCESS = 'CUSTOMER_SUCCESS',
  CORPORATE_COMMUNICATIONS = 'CORPORATE_COMMUNICATIONS',
  CRM = 'CRM',
  RISK_ANALYST = 'RISK_ANALYST',
  FINANCE = 'FINANCE',
  SUPERVISOR_APPROVAL = 'SUPERVISOR_APPROVAL',
  MANAGER_APPROVAL = 'MANAGER_APPROVAL',
}
