export enum OrganizationBusinessSectorEnum {
  SUPPLY = 'SUPPLY',
  SERVICES = 'SERVICES',
  SUPPLY_AND_SERVICES = 'SUPPLY_AND_SERVICES',
  RETAIL = 'RETAIL',
  WHOLESALE = 'WHOLESALE',
  MANUFACTURING = 'MANUFACTURING',
  CONSTRUCTION = 'CONSTRUCTION',
  INFORMATION_AND_COMMUNICATION = 'INFORMATION_AND_COMMUNICATION',
  OTHERS = 'OTHERS',
}
