export enum OrganizationPersonRoleEnum {
  SUPERUSER = 'SUPERUSER',
  CEO = 'CEO',
  COO = 'COO',
  CLIENT_COVERAGE = 'CLIENT_COVERAGE',
  CUSTOMER_SUCCESS = 'CUSTOMER_SUCCESS',
  CORPORATE_COMMUNICATIONS = 'CORPORATE_COMMUNICATIONS',
}
