export enum OrganizationDocumentTypeEnum {
  BUSINESS_REGISTRATION_CERTIFICATE = 'BUSINESS_REGISTRATION_CERTIFICATE',
  TAX_REGISTRATION_CERTIFICATE = 'TAX_REGISTRATION_CERTIFICATE',
  AUDITED_FINANCIAL_STATEMENT = 'AUDITED_FINANCIAL_STATEMENT',
  BANK_STATEMENT = 'BANK_STATEMENT',
  COMPANY_PROFILE = 'COMPANY_PROFILE',
  OTHER = 'OTHER',
}
