export const businessSectors = [
  { name: 'Agriculture And Forestry', code: 'AGRICULTURE_AND_FORESTRY' },
  { name: 'Automotive', code: 'AUTOMOTIVE' },
  {
    name: 'Banking And Financial Services',
    code: 'BANKING_AND_FINANCIAL_SERVICES',
  },
  { name: 'Biotechnology', code: 'BIOTECHNOLOGY' },
  { name: 'Chemicals', code: 'CHEMICALS' },
  {
    name: 'Construction And Real Estate',
    code: 'CONSTRUCTION_AND_REAL_ESTATE',
  },
  { name: 'Consumer Goods', code: 'CONSUMER_GOODS' },
  { name: 'Education And Training', code: 'EDUCATION_AND_TRAINING' },
  { name: 'Energy', code: 'ENERGY' },
  { name: 'Entertainment And Media', code: 'ENTERTAINMENT_AND_MEDIA' },
  { name: 'Environmental Services', code: 'ENVIRONMENTAL_SERVICES' },
  { name: 'Fashion And Apparel', code: 'FASHION_AND_APPAREL' },
  { name: 'Food And Beverage', code: 'FOOD_AND_BEVERAGE' },
  {
    name: 'Healthcare And Pharmaceuticals',
    code: 'HEALTHCARE_AND_PHARMACEUTICALS',
  },
  { name: 'Hospitality And Travel', code: 'HOSPITALITY_AND_TRAVEL' },
  { name: 'Information Technology', code: 'INFORMATION_TECHNOLOGY' },
  { name: 'Insurance', code: 'INSURANCE' },
  { name: 'Legal Services', code: 'LEGAL_SERVICES' },
  {
    name: 'Logistics And Transportation',
    code: 'LOGISTICS_AND_TRANSPORTATION',
  },
  { name: 'Manufacturing', code: 'MANUFACTURING' },
  { name: 'Marketing And Advertising', code: 'MARKETING_AND_ADVERTISING' },
  { name: 'Mining And Metals', code: 'MINING_AND_METALS' },
  { name: 'Non Profit And Ngos', code: 'NON_PROFIT_AND_NGOS' },
  {
    name: 'Public Sector And Government',
    code: 'PUBLIC_SECTOR_AND_GOVERNMENT',
  },
  { name: 'Retail And Wholesale', code: 'RETAIL_AND_WHOLESALE' },
  { name: 'Telecommunications', code: 'TELECOMMUNICATIONS' },
  { name: 'Textiles', code: 'TEXTILES' },
  { name: 'Utilities', code: 'UTILITIES' },
  { name: 'Wholesale Trade', code: 'WHOLESALE_TRADE' },
  { name: 'Others', code: 'OTHERS' },
];
