export const countries = [
  { name: 'Afghanistan', code: 'AF', currencyCode: 'AFN' },
  { name: 'Åland Islands', code: 'AX', currencyCode: 'EUR' },
  { name: 'Albania', code: 'AL', currencyCode: 'ALL' },
  { name: 'Algeria', code: 'DZ', currencyCode: 'DZD' },
  { name: 'American Samoa', code: 'AS', currencyCode: 'USD' },
  { name: 'Andorra', code: 'AD', currencyCode: 'EUR' },
  { name: 'Angola', code: 'AO', currencyCode: 'AOA' },
  { name: 'Anguilla', code: 'AI', currencyCode: 'XCD' },
  { name: 'Antarctica', code: 'AQ', currencyCode: 'XXX' },
  { name: 'Antigua and Barbuda', code: 'AG', currencyCode: 'XCD' },
  { name: 'Argentina', code: 'AR', currencyCode: 'ARS' },
  { name: 'Armenia', code: 'AM', currencyCode: 'AMD' },
  { name: 'Aruba', code: 'AW', currencyCode: 'AWG' },
  { name: 'Australia', code: 'AU', currencyCode: 'AUD' },
  { name: 'Austria', code: 'AT', currencyCode: 'EUR' },
  { name: 'Azerbaijan', code: 'AZ', currencyCode: 'AZN' },
  { name: 'Bahamas', code: 'BS', currencyCode: 'BSD' },
  { name: 'Bahrain', code: 'BH', currencyCode: 'BHD' },
  { name: 'Bangladesh', code: 'BD', currencyCode: 'BDT' },
  { name: 'Barbados', code: 'BB', currencyCode: 'BBD' },
  { name: 'Belarus', code: 'BY', currencyCode: 'BYN' },
  { name: 'Belgium', code: 'BE', currencyCode: 'EUR' },
  { name: 'Belize', code: 'BZ', currencyCode: 'BZD' },
  { name: 'Benin', code: 'BJ', currencyCode: 'XOF' },
  { name: 'Bermuda', code: 'BM', currencyCode: 'BMD' },
  { name: 'Bhutan', code: 'BT', currencyCode: 'BTN' },
  { name: 'Bolivia', code: 'BO', currencyCode: 'BOB' },
  { name: 'Bosnia and Herzegovina', code: 'BA', currencyCode: 'BAM' },
  { name: 'Botswana', code: 'BW', currencyCode: 'BWP' },
  { name: 'Bouvet Island', code: 'BV', currencyCode: 'NOK' },
  { name: 'Brazil', code: 'BR', currencyCode: 'BRL' },
  { name: 'British Indian Ocean Territory', code: 'IO', currencyCode: 'USD' },
  { name: 'Brunei Darussalam', code: 'BN', currencyCode: 'BND' },
  { name: 'Bulgaria', code: 'BG', currencyCode: 'BGN' },
  { name: 'Burkina Faso', code: 'BF', currencyCode: 'XOF' },
  { name: 'Burundi', code: 'BI', currencyCode: 'BIF' },
  { name: 'Cambodia', code: 'KH', currencyCode: 'KHR' },
  { name: 'Cameroon', code: 'CM', currencyCode: 'XAF' },
  { name: 'Canada', code: 'CA', currencyCode: 'CAD' },
  { name: 'Cape Verde', code: 'CV', currencyCode: 'CVE' },
  { name: 'Cayman Islands', code: 'KY', currencyCode: 'KYD' },
  { name: 'Central African Republic', code: 'CF', currencyCode: 'XAF' },
  { name: 'Chad', code: 'TD', currencyCode: 'XAF' },
  { name: 'Chile', code: 'CL', currencyCode: 'CLP' },
  { name: 'China', code: 'CN', currencyCode: 'CNY' },
  { name: 'Christmas Island', code: 'CX', currencyCode: 'AUD' },
  { name: 'Cocos (Keeling) Islands', code: 'CC', currencyCode: 'AUD' },
  { name: 'Colombia', code: 'CO', currencyCode: 'COP' },
  { name: 'Comoros', code: 'KM', currencyCode: 'KMF' },
  { name: 'Congo', code: 'CG', currencyCode: 'XAF' },
  {
    name: 'Congo, The Democratic Republic of the',
    code: 'CD',
    currencyCode: 'CDF',
  },
  { name: 'Cook Islands', code: 'CK', currencyCode: 'NZD' },
  { name: 'Costa Rica', code: 'CR', currencyCode: 'CRC' },
  { name: "Cote D'Ivoire", code: 'CI', currencyCode: 'XOF' },
  { name: 'Croatia', code: 'HR', currencyCode: 'HRK' },
  { name: 'Cuba', code: 'CU', currencyCode: 'CUP' },
  { name: 'Cyprus', code: 'CY', currencyCode: 'EUR' },
  { name: 'Czech Republic', code: 'CZ', currencyCode: 'CZK' },
  { name: 'Denmark', code: 'DK', currencyCode: 'DKK' },
  { name: 'Djibouti', code: 'DJ', currencyCode: 'DJF' },
  { name: 'Dominica', code: 'DM', currencyCode: 'XCD' },
  { name: 'Dominican Republic', code: 'DO', currencyCode: 'DOP' },
  { name: 'Ecuador', code: 'EC', currencyCode: 'USD' },
  { name: 'Egypt', code: 'EG', currencyCode: 'EGP' },
  { name: 'El Salvador', code: 'SV', currencyCode: 'USD' },
  { name: 'Equatorial Guinea', code: 'GQ', currencyCode: 'XAF' },
  { name: 'Eritrea', code: 'ER', currencyCode: 'ERN' },
  { name: 'Estonia', code: 'EE', currencyCode: 'EUR' },
  { name: 'Ethiopia', code: 'ET', currencyCode: 'ETB' },
  { name: 'Falkland Islands (Malvinas)', code: 'FK', currencyCode: 'FKP' },
  { name: 'Faroe Islands', code: 'FO', currencyCode: 'DKK' },
  { name: 'Fiji', code: 'FJ', currencyCode: 'FJD' },
  { name: 'Finland', code: 'FI', currencyCode: 'EUR' },
  { name: 'France', code: 'FR', currencyCode: 'EUR' },
  { name: 'French Guiana', code: 'GF', currencyCode: 'EUR' },
  { name: 'French Polynesia', code: 'PF', currencyCode: 'XPF' },
  { name: 'French Southern Territories', code: 'TF', currencyCode: 'EUR' },
  { name: 'Gabon', code: 'GA', currencyCode: 'XAF' },
  { name: 'Gambia', code: 'GM', currencyCode: 'GMD' },
  { name: 'Georgia', code: 'GE', currencyCode: 'GEL' },
  { name: 'Germany', code: 'DE', currencyCode: 'EUR' },
  { name: 'Ghana', code: 'GH', currencyCode: 'GHS' },
  { name: 'Gibraltar', code: 'GI', currencyCode: 'GIP' },
  { name: 'Greece', code: 'GR', currencyCode: 'EUR' },
  { name: 'Greenland', code: 'GL', currencyCode: 'DKK' },
  { name: 'Grenada', code: 'GD', currencyCode: 'XCD' },
  { name: 'Guadeloupe', code: 'GP', currencyCode: 'EUR' },
  { name: 'Guam', code: 'GU', currencyCode: 'USD' },
  { name: 'Guatemala', code: 'GT', currencyCode: 'GTQ' },
  { name: 'Guernsey', code: 'GG', currencyCode: 'GBP' },
  { name: 'Guinea', code: 'GN', currencyCode: 'GNF' },
  { name: 'Guinea-Bissau', code: 'GW', currencyCode: 'XOF' },
  { name: 'Guyana', code: 'GY', currencyCode: 'GYD' },
  { name: 'Haiti', code: 'HT', currencyCode: 'HTG' },
  {
    name: 'Heard Island and Mcdonald Islands',
    code: 'HM',
    currencyCode: 'AUD',
  },
  { name: 'Holy See (Vatican City State)', code: 'VA', currencyCode: 'EUR' },
  { name: 'Honduras', code: 'HN', currencyCode: 'HNL' },
  { name: 'Hong Kong', code: 'HK', currencyCode: 'HKD' },
  { name: 'Hungary', code: 'HU', currencyCode: 'HUF' },
  { name: 'Iceland', code: 'IS', currencyCode: 'ISK' },
  { name: 'India', code: 'IN', currencyCode: 'INR' },
  { name: 'Indonesia', code: 'ID', currencyCode: 'IDR' },
  { name: 'Iran, Islamic Republic Of', code: 'IR', currencyCode: 'IRR' },
  { name: 'Iraq', code: 'IQ', currencyCode: 'IQD' },
  { name: 'Ireland', code: 'IE', currencyCode: 'EUR' },
  { name: 'Isle of Man', code: 'IM', currencyCode: 'GBP' },
  { name: 'Israel', code: 'IL', currencyCode: 'ILS' },
  { name: 'Italy', code: 'IT', currencyCode: 'EUR' },
  { name: 'Jamaica', code: 'JM', currencyCode: 'JMD' },
  { name: 'Japan', code: 'JP', currencyCode: 'JPY' },
  { name: 'Jersey', code: 'JE', currencyCode: 'GBP' },
  { name: 'Jordan', code: 'JO', currencyCode: 'JOD' },
  { name: 'Kazakhstan', code: 'KZ', currencyCode: 'KZT' },
  { name: 'Kenya', code: 'KE', currencyCode: 'KES' },
  { name: 'Kiribati', code: 'KI', currencyCode: 'AUD' },
  {
    name: "Korea, Democratic People'S Republic of",
    code: 'KP',
    currencyCode: 'KPW',
  },
  { name: 'Korea, Republic of', code: 'KR', currencyCode: 'KRW' },
  { name: 'Kuwait', code: 'KW', currencyCode: 'KWD' },
  { name: 'Kyrgyzstan', code: 'KG', currencyCode: 'KGS' },
  { name: "Lao People'S Democratic Republic", code: 'LA', currencyCode: 'LAK' },
  { name: 'Latvia', code: 'LV', currencyCode: 'EUR' },
  { name: 'Lebanon', code: 'LB', currencyCode: 'LBP' },
  { name: 'Lesotho', code: 'LS', currencyCode: 'LSL' },
  { name: 'Liberia', code: 'LR', currencyCode: 'LRD' },
  { name: 'Libyan Arab Jamahiriya', code: 'LY', currencyCode: 'LYD' },
  { name: 'Liechtenstein', code: 'LI', currencyCode: 'CHF' },
  { name: 'Lithuania', code: 'LT', currencyCode: 'EUR' },
  { name: 'Luxembourg', code: 'LU', currencyCode: 'EUR' },
  { name: 'Macao', code: 'MO', currencyCode: 'MOP' },
  {
    name: 'Macedonia, The Former Yugoslav Republic of',
    code: 'MK',
    currencyCode: 'MKD',
  },
  { name: 'Madagascar', code: 'MG', currencyCode: 'MGA' },
  { name: 'Malawi', code: 'MW', currencyCode: 'MWK' },
  { name: 'Malaysia', code: 'MY', currencyCode: 'MYR' },
  { name: 'Maldives', code: 'MV', currencyCode: 'MVR' },
  { name: 'Mali', code: 'ML', currencyCode: 'XOF' },
  { name: 'Malta', code: 'MT', currencyCode: 'EUR' },
  { name: 'Marshall Islands', code: 'MH', currencyCode: 'USD' },
  { name: 'Martinique', code: 'MQ', currencyCode: 'EUR' },
  { name: 'Mauritania', code: 'MR', currencyCode: 'MRU' },
  { name: 'Mauritius', code: 'MU', currencyCode: 'MUR' },
  { name: 'Mayotte', code: 'YT', currencyCode: 'EUR' },
  { name: 'Mexico', code: 'MX', currencyCode: 'MXN' },
  { name: 'Micronesia, Federated States of', code: 'FM', currencyCode: 'USD' },
  { name: 'Moldova, Republic of', code: 'MD', currencyCode: 'MDL' },
  { name: 'Monaco', code: 'MC', currencyCode: 'EUR' },
  { name: 'Mongolia', code: 'MN', currencyCode: 'MNT' },
  { name: 'Montserrat', code: 'MS', currencyCode: 'XCD' },
  { name: 'Morocco', code: 'MA', currencyCode: 'MAD' },
  { name: 'Mozambique', code: 'MZ', currencyCode: 'MZN' },
  { name: 'Myanmar', code: 'MM', currencyCode: 'MMK' },
  { name: 'Namibia', code: 'NA', currencyCode: 'NAD' },
  { name: 'Nauru', code: 'NR', currencyCode: 'AUD' },
  { name: 'Nepal', code: 'NP', currencyCode: 'NPR' },
  { name: 'Netherlands', code: 'NL', currencyCode: 'EUR' },
  { name: 'Netherlands Antilles', code: 'AN', currencyCode: 'ANG' },
  { name: 'New Caledonia', code: 'NC', currencyCode: 'XPF' },
  { name: 'New Zealand', code: 'NZ', currencyCode: 'NZD' },
  { name: 'Nicaragua', code: 'NI', currencyCode: 'NIO' },
  { name: 'Niger', code: 'NE', currencyCode: 'XOF' },
  { name: 'Nigeria', code: 'NG', currencyCode: 'NGN' },
  { name: 'Niue', code: 'NU', currencyCode: 'NZD' },
  { name: 'Norfolk Island', code: 'NF', currencyCode: 'AUD' },
  { name: 'Northern Mariana Islands', code: 'MP', currencyCode: 'USD' },
  { name: 'Norway', code: 'NO', currencyCode: 'NOK' },
  { name: 'Oman', code: 'OM', currencyCode: 'OMR' },
  { name: 'Pakistan', code: 'PK', currencyCode: 'PKR' },
  { name: 'Palau', code: 'PW', currencyCode: 'USD' },
  { name: 'Palestinian Territory, Occupied', code: 'PS', currencyCode: 'ILS' },
  { name: 'Panama', code: 'PA', currencyCode: 'PAB' },
  { name: 'Papua New Guinea', code: 'PG', currencyCode: 'PGK' },
  { name: 'Paraguay', code: 'PY', currencyCode: 'PYG' },
  { name: 'Peru', code: 'PE', currencyCode: 'PEN' },
  { name: 'Philippines', code: 'PH', currencyCode: 'PHP' },
  { name: 'Pitcairn', code: 'PN', currencyCode: 'NZD' },
  { name: 'Poland', code: 'PL', currencyCode: 'PLN' },
  { name: 'Portugal', code: 'PT', currencyCode: 'EUR' },
  { name: 'Puerto Rico', code: 'PR', currencyCode: 'USD' },
  { name: 'Qatar', code: 'QA', currencyCode: 'QAR' },
  { name: 'Reunion', code: 'RE', currencyCode: 'EUR' },
  { name: 'Romania', code: 'RO', currencyCode: 'RON' },
  { name: 'Russian Federation', code: 'RU', currencyCode: 'RUB' },
  { name: 'RWANDA', code: 'RW', currencyCode: 'RWF' },
  { name: 'Saint Helena', code: 'SH', currencyCode: 'SHP' },
  { name: 'Saint Kitts and Nevis', code: 'KN', currencyCode: 'XCD' },
  { name: 'Saint Lucia', code: 'LC', currencyCode: 'XCD' },
  { name: 'Saint Pierre and Miquelon', code: 'PM', currencyCode: 'EUR' },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', currencyCode: 'XCD' },
  { name: 'Samoa', code: 'WS', currencyCode: 'WST' },
  { name: 'San Marino', code: 'SM', currencyCode: 'EUR' },
  { name: 'Sao Tome and Principe', code: 'ST', currencyCode: 'STN' },
  { name: 'Saudi Arabia', code: 'SA', currencyCode: 'SAR' },
  { name: 'Senegal', code: 'SN', currencyCode: 'XOF' },
  { name: 'Serbia and Montenegro', code: 'CS', currencyCode: 'RSD' },
  { name: 'Seychelles', code: 'SC', currencyCode: 'SCR' },
  { name: 'Sierra Leone', code: 'SL', currencyCode: 'SLL' },
  { name: 'Singapore', code: 'SG', currencyCode: 'SGD' },
  { name: 'Slovakia', code: 'SK', currencyCode: 'EUR' },
  { name: 'Slovenia', code: 'SI', currencyCode: 'EUR' },
  { name: 'Solomon Islands', code: 'SB', currencyCode: 'SBD' },
  { name: 'Somalia', code: 'SO', currencyCode: 'SOS' },
  { name: 'South Africa', code: 'ZA', currencyCode: 'ZAR' },
  {
    name: 'South Georgia and the South Sandwich Islands',
    code: 'GS',
    currencyCode: 'GBP',
  },
  { name: 'Spain', code: 'ES', currencyCode: 'EUR' },
  { name: 'Sri Lanka', code: 'LK', currencyCode: 'LKR' },
  { name: 'Sudan', code: 'SD', currencyCode: 'SDG' },
  { name: 'Suriname', code: 'SR', currencyCode: 'SRD' },
  { name: 'Svalbard and Jan Mayen', code: 'SJ', currencyCode: 'NOK' },
  { name: 'Swaziland', code: 'SZ', currencyCode: 'SZL' },
  { name: 'Sweden', code: 'SE', currencyCode: 'SEK' },
  { name: 'Switzerland', code: 'CH', currencyCode: 'CHF' },
  { name: 'Syrian Arab Republic', code: 'SY', currencyCode: 'SYP' },
  { name: 'Taiwan, Province of China', code: 'TW', currencyCode: 'TWD' },
  { name: 'Tajikistan', code: 'TJ', currencyCode: 'TJS' },
  { name: 'Tanzania, United Republic of', code: 'TZ', currencyCode: 'TZS' },
  { name: 'Thailand', code: 'TH', currencyCode: 'THB' },
  { name: 'Timor-Leste', code: 'TL', currencyCode: 'USD' },
  { name: 'Togo', code: 'TG', currencyCode: 'XOF' },
  { name: 'Tokelau', code: 'TK', currencyCode: 'NZD' },
  { name: 'Tonga', code: 'TO', currencyCode: 'TOP' },
  { name: 'Trinidad and Tobago', code: 'TT', currencyCode: 'TTD' },
  { name: 'Tunisia', code: 'TN', currencyCode: 'TND' },
  { name: 'Turkey', code: 'TR', currencyCode: 'TRY' },
  { name: 'Turkmenistan', code: 'TM', currencyCode: 'TMT' },
  { name: 'Turks and Caicos Islands', code: 'TC', currencyCode: 'USD' },
  { name: 'Tuvalu', code: 'TV', currencyCode: 'AUD' },
  { name: 'Uganda', code: 'UG', currencyCode: 'UGX' },
  { name: 'Ukraine', code: 'UA', currencyCode: 'UAH' },
  { name: 'United Arab Emirates', code: 'AE', currencyCode: 'AED' },
  { name: 'United Kingdom', code: 'GB', currencyCode: 'GBP' },
  { name: 'United States', code: 'US', currencyCode: 'USD' },
  {
    name: 'United States Minor Outlying Islands',
    code: 'UM',
    currencyCode: 'USD',
  },
  { name: 'Uruguay', code: 'UY', currencyCode: 'UYU' },
  { name: 'Uzbekistan', code: 'UZ', currencyCode: 'UZS' },
  { name: 'Vanuatu', code: 'VU', currencyCode: 'VUV' },
  { name: 'Venezuela', code: 'VE', currencyCode: 'VES' },
  { name: 'Viet Nam', code: 'VN', currencyCode: 'VND' },
  { name: 'Virgin Islands, British', code: 'VG', currencyCode: 'USD' },
  { name: 'Virgin Islands, U.S.', code: 'VI', currencyCode: 'USD' },
  { name: 'Wallis and Futuna', code: 'WF', currencyCode: 'XPF' },
  { name: 'Western Sahara', code: 'EH', currencyCode: 'MAD' },
  { name: 'Yemen', code: 'YE', currencyCode: 'YER' },
  { name: 'Zambia', code: 'ZM', currencyCode: 'ZMW' },
  { name: 'Zimbabwe', code: 'ZW', currencyCode: 'USD' },
];

export const currencyList = [
  { label: 'AED', value: 'AED' },
  { label: 'AFN', value: 'AFN' },
  { label: 'ALL', value: 'ALL' },
  { label: 'AMD', value: 'AMD' },
  { label: 'ANG', value: 'ANG' },
  { label: 'AOA', value: 'AOA' },
  { label: 'ARS', value: 'ARS' },
  { label: 'AUD', value: 'AUD' },
  { label: 'AWG', value: 'AWG' },
  { label: 'AZN', value: 'AZN' },
  { label: 'BAM', value: 'BAM' },
  { label: 'BBD', value: 'BBD' },
  { label: 'BDT', value: 'BDT' },
  { label: 'BGN', value: 'BGN' },
  { label: 'BHD', value: 'BHD' },
  { label: 'BIF', value: 'BIF' },
  { label: 'BMD', value: 'BMD' },
  { label: 'BND', value: 'BND' },
  { label: 'BOB', value: 'BOB' },
  { label: 'BRL', value: 'BRL' },
  { label: 'BSD', value: 'BSD' },
  { label: 'BTN', value: 'BTN' },
  { label: 'BWP', value: 'BWP' },
  { label: 'BYN', value: 'BYN' },
  { label: 'BZD', value: 'BZD' },
  { label: 'CAD', value: 'CAD' },
  { label: 'CDF', value: 'CDF' },
  { label: 'CHF', value: 'CHF' },
  { label: 'CLP', value: 'CLP' },
  { label: 'CNY', value: 'CNY' },
  { label: 'COP', value: 'COP' },
  { label: 'CRC', value: 'CRC' },
  { label: 'CUP', value: 'CUP' },
  { label: 'CVE', value: 'CVE' },
  { label: 'CZK', value: 'CZK' },
  { label: 'DJF', value: 'DJF' },
  { label: 'DKK', value: 'DKK' },
  { label: 'DOP', value: 'DOP' },
  { label: 'DZD', value: 'DZD' },
  { label: 'EGP', value: 'EGP' },
  { label: 'ERN', value: 'ERN' },
  { label: 'ETB', value: 'ETB' },
  { label: 'EUR', value: 'EUR' },
  { label: 'FJD', value: 'FJD' },
  { label: 'FKP', value: 'FKP' },
  { label: 'FOK', value: 'FOK' },
  { label: 'GBP', value: 'GBP' },
  { label: 'GEL', value: 'GEL' },
  { label: 'GGP', value: 'GGP' },
  { label: 'GHS', value: 'GHS' },
  { label: 'GIP', value: 'GIP' },
  { label: 'GMD', value: 'GMD' },
  { label: 'GNF', value: 'GNF' },
  { label: 'GTQ', value: 'GTQ' },
  { label: 'GYD', value: 'GYD' },
  { label: 'HKD', value: 'HKD' },
  { label: 'HNL', value: 'HNL' },
  { label: 'HRK', value: 'HRK' },
  { label: 'HTG', value: 'HTG' },
  { label: 'HUF', value: 'HUF' },
  { label: 'IDR', value: 'IDR' },
  { label: 'ILS', value: 'ILS' },
  { label: 'IMP', value: 'IMP' },
  { label: 'INR', value: 'INR' },
  { label: 'IQD', value: 'IQD' },
  { label: 'IRR', value: 'IRR' },
  { label: 'ISK', value: 'ISK' },
  { label: 'JEP', value: 'JEP' },
  { label: 'JMD', value: 'JMD' },
  { label: 'JOD', value: 'JOD' },
  { label: 'JPY', value: 'JPY' },
  { label: 'KES', value: 'KES' },
  { label: 'KGS', value: 'KGS' },
  { label: 'KHR', value: 'KHR' },
  { label: 'KID', value: 'KID' },
  { label: 'KMF', value: 'KMF' },
  { label: 'KRW', value: 'KRW' },
  { label: 'KWD', value: 'KWD' },
  { label: 'KYD', value: 'KYD' },
  { label: 'KZT', value: 'KZT' },
  { label: 'LAK', value: 'LAK' },
  { label: 'LBP', value: 'LBP' },
  { label: 'LKR', value: 'LKR' },
  { label: 'LRD', value: 'LRD' },
  { label: 'LSL', value: 'LSL' },
  { label: 'LYD', value: 'LYD' },
  { label: 'MAD', value: 'MAD' },
  { label: 'MDL', value: 'MDL' },
  { label: 'MGA', value: 'MGA' },
  { label: 'MKD', value: 'MKD' },
  { label: 'MMK', value: 'MMK' },
  { label: 'MNT', value: 'MNT' },
  { label: 'MOP', value: 'MOP' },
  { label: 'MRU', value: 'MRU' },
  { label: 'MUR', value: 'MUR' },
  { label: 'MVR', value: 'MVR' },
  { label: 'MWK', value: 'MWK' },
  { label: 'MXN', value: 'MXN' },
  { label: 'MYR', value: 'MYR' },
  { label: 'MZN', value: 'MZN' },
  { label: 'NAD', value: 'NAD' },
  { label: 'NGN', value: 'NGN' },
  { label: 'NIO', value: 'NIO' },
  { label: 'NOK', value: 'NOK' },
  { label: 'NPR', value: 'NPR' },
  { label: 'NZD', value: 'NZD' },
  { label: 'OMR', value: 'OMR' },
  { label: 'PAB', value: 'PAB' },
  { label: 'PEN', value: 'PEN' },
  { label: 'PGK', value: 'PGK' },
  { label: 'PHP', value: 'PHP' },
  { label: 'PKR', value: 'PKR' },
  { label: 'PLN', value: 'PLN' },
  { label: 'PYG', value: 'PYG' },
  { label: 'QAR', value: 'QAR' },
  { label: 'RON', value: 'RON' },
  { label: 'RSD', value: 'RSD' },
  { label: 'RUB', value: 'RUB' },
  { label: 'RWF', value: 'RWF' },
  { label: 'SAR', value: 'SAR' },
  { label: 'SBD', value: 'SBD' },
  { label: 'SCR', value: 'SCR' },
  { label: 'SDG', value: 'SDG' },
  { label: 'SEK', value: 'SEK' },
  { label: 'SGD', value: 'SGD' },
  { label: 'SHP', value: 'SHP' },
  { label: 'SLE', value: 'SLE' },
  { label: 'SLL', value: 'SLL' },
  { label: 'SOS', value: 'SOS' },
  { label: 'SRD', value: 'SRD' },
  { label: 'SSP', value: 'SSP' },
  { label: 'STN', value: 'STN' },
  { label: 'SYP', value: 'SYP' },
  { label: 'SZL', value: 'SZL' },
  { label: 'THB', value: 'THB' },
  { label: 'TJS', value: 'TJS' },
  { label: 'TMT', value: 'TMT' },
  { label: 'TND', value: 'TND' },
  { label: 'TOP', value: 'TOP' },
  { label: 'TRY', value: 'TRY' },
  { label: 'TTD', value: 'TTD' },
  { label: 'TVD', value: 'TVD' },
  { label: 'TWD', value: 'TWD' },
  { label: 'TZS', value: 'TZS' },
  { label: 'UAH', value: 'UAH' },
  { label: 'UGX', value: 'UGX' },
  { label: 'USD', value: 'USD' },
  { label: 'UYU', value: 'UYU' },
  { label: 'UZS', value: 'UZS' },
  { label: 'VES', value: 'VES' },
  { label: 'VND', value: 'VND' },
  { label: 'VUV', value: 'VUV' },
  { label: 'WST', value: 'WST' },
  { label: 'XAF', value: 'XAF' },
  { label: 'XCD', value: 'XCD' },
  { label: 'XOF', value: 'XOF' },
  { label: 'XPF', value: 'XPF' },
  { label: 'YER', value: 'YER' },
  { label: 'ZAR', value: 'ZAR' },
  { label: 'ZMW', value: 'ZMW' },
  { label: 'ZWL', value: 'ZWL' },
];

export const countriesData = [
  {
    name: 'Afghanistan',
    dial_code: '+93',
    emoji: '🇦🇫',
    code: 'AF',
    timezone: 'Asia/Kabul',
  },
  {
    name: 'Aland Islands',
    dial_code: '+358',
    emoji: '🇦🇽',
    code: 'AX',
    timezone: 'Europe/Mariehamn',
  },
  {
    name: 'Albania',
    dial_code: '+355',
    emoji: '🇦🇱',
    code: 'AL',
    timezone: 'Europe/Tirane',
  },
  {
    name: 'Algeria',
    dial_code: '+213',
    emoji: '🇩🇿',
    code: 'DZ',
    timezone: 'Africa/Algiers',
  },
  {
    name: 'AmericanSamoa',
    dial_code: '+1684',
    emoji: '🇦🇸',
    code: 'AS',
    timezone: 'Pacific/Pago_Pago',
  },
  {
    name: 'Andorra',
    dial_code: '+376',
    emoji: '🇦🇩',
    code: 'AD',
    timezone: 'Europe/Andorra',
  },
  {
    name: 'Angola',
    dial_code: '+244',
    emoji: '🇦🇴',
    code: 'AO',
    timezone: 'Africa/Luanda',
  },
  {
    name: 'Anguilla',
    dial_code: '+1264',
    emoji: '🇦🇮',
    code: 'AI',
    timezone: 'America/Anguilla',
  },
  {
    name: 'Antarctica',
    dial_code: '+672',
    emoji: '🇦🇶',
    code: 'AQ',
    timezone: 'Antarctica/McMurdo',
  },
  {
    name: 'Antigua and Barbuda',
    dial_code: '+1268',
    emoji: '🇦🇬',
    code: 'AG',
    timezone: 'America/Antigua',
  },
  {
    name: 'Argentina',
    dial_code: '+54',
    emoji: '🇦🇷',
    code: 'AR',
    timezone: 'America/Argentina/Buenos_Aires',
  },
  {
    name: 'Armenia',
    dial_code: '+374',
    emoji: '🇦🇲',
    code: 'AM',
    timezone: 'Asia/Yerevan',
  },
  {
    name: 'Aruba',
    dial_code: '+297',
    emoji: '🇦🇼',
    code: 'AW',
    timezone: 'America/Aruba',
  },
  {
    name: 'Australia',
    dial_code: '+61',
    emoji: '🇦🇺',
    code: 'AU',
    timezone: 'Australia/Sydney',
  },
  {
    name: 'Austria',
    dial_code: '+43',
    emoji: '🇦🇹',
    code: 'AT',
    timezone: 'Europe/Vienna',
  },
  {
    name: 'Azerbaijan',
    dial_code: '+994',
    emoji: '🇦🇿',
    code: 'AZ',
    timezone: 'Asia/Baku',
  },
  {
    name: 'Bahamas',
    dial_code: '+1242',
    emoji: '🇧🇸',
    code: 'BS',
    timezone: 'America/Nassau',
  },
  {
    name: 'Bahrain',
    dial_code: '+973',
    emoji: '🇧🇭',
    code: 'BH',
    timezone: 'Asia/Bahrain',
  },
  {
    name: 'Bangladesh',
    dial_code: '+880',
    emoji: '🇧🇩',
    code: 'BD',
    timezone: 'Asia/Dhaka',
  },
  {
    name: 'Barbados',
    dial_code: '+1246',
    emoji: '🇧🇧',
    code: 'BB',
    timezone: 'America/Barbados',
  },
  {
    name: 'Belarus',
    dial_code: '+375',
    emoji: '🇧🇾',
    code: 'BY',
    timezone: 'Europe/Minsk',
  },
  {
    name: 'Belgium',
    dial_code: '+32',
    emoji: '🇧🇪',
    code: 'BE',
    timezone: 'Europe/Brussels',
  },
  {
    name: 'Belize',
    dial_code: '+501',
    emoji: '🇧🇿',
    code: 'BZ',
    timezone: 'America/Belize',
  },
  {
    name: 'Benin',
    dial_code: '+229',
    emoji: '🇧🇯',
    code: 'BJ',
    timezone: 'Africa/Porto-Novo',
  },
  {
    name: 'Bermuda',
    dial_code: '+1441',
    emoji: '🇧🇲',
    code: 'BM',
    timezone: 'Atlantic/Bermuda',
  },
  {
    name: 'Bhutan',
    dial_code: '+975',
    emoji: '🇧🇹',
    code: 'BT',
    timezone: 'Asia/Thimphu',
  },
  {
    name: 'Bolivia, Plurinational State of',
    dial_code: '+591',
    emoji: '🇧🇴',
    code: 'BO',
    timezone: 'America/La_Paz',
  },
  {
    name: 'Bosnia and Herzegovina',
    dial_code: '+387',
    emoji: '🇧🇦',
    code: 'BA',
    timezone: 'Europe/Sarajevo',
  },
  {
    name: 'Botswana',
    dial_code: '+267',
    emoji: '🇧🇼',
    code: 'BW',
    timezone: 'Africa/Gaborone',
  },
  {
    name: 'Brazil',
    dial_code: '+55',
    emoji: '🇧🇷',
    code: 'BR',
    timezone: 'America/Sao_Paulo',
  },
  {
    name: 'British Indian Ocean Territory',
    dial_code: '+246',
    emoji: '🇮🇴',
    code: 'IO',
    timezone: 'Indian/Chagos',
  },
  {
    name: 'Brunei Darussalam',
    dial_code: '+673',
    emoji: '🇧🇳',
    code: 'BN',
    timezone: 'Asia/Brunei',
  },
  {
    name: 'Bulgaria',
    dial_code: '+359',
    emoji: '🇧🇬',
    code: 'BG',
    timezone: 'Europe/Sofia',
  },
  {
    name: 'Burkina Faso',
    dial_code: '+226',
    emoji: '🇧🇫',
    code: 'BF',
    timezone: 'Africa/Ouagadougou',
  },
  {
    name: 'Burundi',
    dial_code: '+257',
    emoji: '🇧🇮',
    code: 'BI',
    timezone: 'Africa/Bujumbura',
  },
  {
    name: 'Cambodia',
    dial_code: '+855',
    emoji: '🇰🇭',
    code: 'KH',
    timezone: 'Asia/Phnom_Penh',
  },
  {
    name: 'Cameroon',
    dial_code: '+237',
    emoji: '🇨🇲',
    code: 'CM',
    timezone: 'Africa/Douala',
  },
  {
    name: 'Canada',
    dial_code: '+1',
    emoji: '🇨🇦',
    code: 'CA',
    timezone: 'America/Toronto',
  },
  {
    name: 'Cape Verde',
    dial_code: '+238',
    emoji: '🇨🇻',
    code: 'CV',
    timezone: 'Atlantic/Cape_Verde',
  },
  {
    name: 'Cayman Islands',
    dial_code: '+345',
    emoji: '🇰🇾',
    code: 'KY',
    timezone: 'America/Cayman',
  },
  {
    name: 'Central African Republic',
    dial_code: '+236',
    emoji: '🇨🇫',
    code: 'CF',
    timezone: 'Africa/Bangui',
  },
  {
    name: 'Chad',
    dial_code: '+235',
    emoji: '🇹🇩',
    code: 'TD',
    timezone: 'Africa/Ndjamena',
  },
  {
    name: 'Chile',
    dial_code: '+56',
    emoji: '🇨🇱',
    code: 'CL',
    timezone: 'America/Santiago',
  },
  {
    name: 'China',
    dial_code: '+86',
    emoji: '🇨🇳',
    code: 'CN',
    timezone: 'Asia/Shanghai',
  },
  {
    name: 'Christmas Island',
    dial_code: '+61',
    emoji: '🇨🇽',
    code: 'CX',
    timezone: 'Indian/Christmas',
  },
  {
    name: 'Cocos (Keeling) Islands',
    dial_code: '+61',
    emoji: '🇨🇨',
    code: 'CC',
    timezone: 'Indian/Cocos',
  },
  {
    name: 'Colombia',
    dial_code: '+57',
    emoji: '🇨🇴',
    code: 'CO',
    timezone: 'America/Bogota',
  },
  {
    name: 'Comoros',
    dial_code: '+269',
    emoji: '🇰🇲',
    code: 'KM',
    timezone: 'Indian/Comoro',
  },
  {
    name: 'Congo',
    dial_code: '+242',
    emoji: '🇨🇬',
    code: 'CG',
    timezone: 'Africa/Brazzaville',
  },
  {
    name: 'Congo, The Democratic Republic of the Congo',
    dial_code: '+243',
    emoji: '🇨🇩',
    code: 'CD',
    timezone: 'Africa/Kinshasa',
  },
  {
    name: 'Cook Islands',
    dial_code: '+682',
    emoji: '🇨🇰',
    code: 'CK',
    timezone: 'Pacific/Rarotonga',
  },
  {
    name: 'Costa Rica',
    dial_code: '+506',
    emoji: '🇨🇷',
    code: 'CR',
    timezone: 'America/Costa_Rica',
  },
  {
    name: "Cote d'Ivoire",
    dial_code: '+225',
    emoji: '🇨🇮',
    code: 'CI',
    timezone: 'Africa/Abidjan',
  },
  {
    name: 'Croatia',
    dial_code: '+385',
    emoji: '🇭🇷',
    code: 'HR',
    timezone: 'Europe/Zagreb',
  },
  {
    name: 'Cuba',
    dial_code: '+53',
    emoji: '🇨🇺',
    code: 'CU',
    timezone: 'America/Havana',
  },
  {
    name: 'Cyprus',
    dial_code: '+357',
    emoji: '🇨🇾',
    code: 'CY',
    timezone: 'Asia/Nicosia',
  },
  {
    name: 'Czech Republic',
    dial_code: '+420',
    emoji: '🇨🇿',
    code: 'CZ',
    timezone: 'Europe/Prague',
  },
  {
    name: 'Denmark',
    dial_code: '+45',
    emoji: '🇩🇰',
    code: 'DK',
    timezone: 'Europe/Copenhagen',
  },
  {
    name: 'Djibouti',
    dial_code: '+253',
    emoji: '🇩🇯',
    code: 'DJ',
    timezone: 'Africa/Djibouti',
  },
  {
    name: 'Dominica',
    dial_code: '+1767',
    emoji: '🇩🇲',
    code: 'DM',
    timezone: 'America/Dominica',
  },
  {
    name: 'Dominican Republic',
    dial_code: '+1849',
    emoji: '🇩🇴',
    code: 'DO',
    timezone: 'America/Santo_Domingo',
  },
  {
    name: 'Ecuador',
    dial_code: '+593',
    emoji: '🇪🇨',
    code: 'EC',
    timezone: 'America/Guayaquil',
  },
  {
    name: 'Egypt',
    dial_code: '+20',
    emoji: '🇪🇬',
    code: 'EG',
    timezone: 'Africa/Cairo',
  },
  {
    name: 'El Salvador',
    dial_code: '+503',
    emoji: '🇸🇻',
    code: 'SV',
    timezone: 'America/El_Salvador',
  },
  {
    name: 'Equatorial Guinea',
    dial_code: '+240',
    emoji: '🇬🇶',
    code: 'GQ',
    timezone: 'Africa/Malabo',
  },
  {
    name: 'Eritrea',
    dial_code: '+291',
    emoji: '🇪🇷',
    code: 'ER',
    timezone: 'Africa/Asmara',
  },
  {
    name: 'Estonia',
    dial_code: '+372',
    emoji: '🇪🇪',
    code: 'EE',
    timezone: 'Europe/Tallinn',
  },
  {
    name: 'Ethiopia',
    dial_code: '+251',
    emoji: '🇪🇹',
    code: 'ET',
    timezone: 'Africa/Addis_Ababa',
  },
  {
    name: 'Falkland Islands (Malvinas)',
    dial_code: '+500',
    emoji: '🇫🇰',
    code: 'FK',
    timezone: 'Atlantic/Stanley',
  },
  {
    name: 'Faroe Islands',
    dial_code: '+298',
    emoji: '🇫🇴',
    code: 'FO',
    timezone: 'Atlantic/Faroe',
  },
  {
    name: 'Fiji',
    dial_code: '+679',
    emoji: '🇫🇯',
    code: 'FJ',
    timezone: 'Pacific/Fiji',
  },
  {
    name: 'Finland',
    dial_code: '+358',
    emoji: '🇫🇮',
    code: 'FI',
    timezone: 'Europe/Helsinki',
  },
  {
    name: 'France',
    dial_code: '+33',
    emoji: '🇫🇷',
    code: 'FR',
    timezone: 'Europe/Paris',
  },
  {
    name: 'French Guiana',
    dial_code: '+594',
    emoji: '🇬🇫',
    code: 'GF',
    timezone: 'America/Cayenne',
  },
  {
    name: 'French Polynesia',
    dial_code: '+689',
    emoji: '🇵🇫',
    code: 'PF',
    timezone: 'Pacific/Tahiti',
  },
  {
    name: 'Gabon',
    dial_code: '+241',
    emoji: '🇬🇦',
    code: 'GA',
    timezone: 'Africa/Libreville',
  },
  {
    name: 'Gambia',
    dial_code: '+220',
    emoji: '🇬🇲',
    code: 'GM',
    timezone: 'Africa/Banjul',
  },
  {
    name: 'Georgia',
    dial_code: '+995',
    emoji: '🇬🇪',
    code: 'GE',
    timezone: 'Asia/Tbilisi',
  },
  {
    name: 'Germany',
    dial_code: '+49',
    emoji: '🇩🇪',
    code: 'DE',
    timezone: 'Europe/Berlin',
  },
  {
    name: 'Ghana',
    dial_code: '+233',
    emoji: '🇬🇭',
    code: 'GH',
    timezone: 'Africa/Accra',
  },
  {
    name: 'Gibraltar',
    dial_code: '+350',
    emoji: '🇬🇮',
    code: 'GI',
    timezone: 'Europe/Gibraltar',
  },
  {
    name: 'Greece',
    dial_code: '+30',
    emoji: '🇬🇷',
    code: 'GR',
    timezone: 'Europe/Athens',
  },
  {
    name: 'Greenland',
    dial_code: '+299',
    emoji: '🇬🇱',
    code: 'GL',
    timezone: 'America/Godthab',
  },
  {
    name: 'Grenada',
    dial_code: '+1473',
    emoji: '🇬🇩',
    code: 'GD',
    timezone: 'America/Grenada',
  },
  {
    name: 'Guadeloupe',
    dial_code: '+590',
    emoji: '🇬🇵',
    code: 'GP',
    timezone: 'America/Guadeloupe',
  },
  {
    name: 'Guam',
    dial_code: '+1671',
    emoji: '🇬🇺',
    code: 'GU',
    timezone: 'Pacific/Guam',
  },
  {
    name: 'Guatemala',
    dial_code: '+502',
    emoji: '🇬🇹',
    code: 'GT',
    timezone: 'America/Guatemala',
  },
  {
    name: 'Guernsey',
    dial_code: '+44',
    emoji: '🇬🇬',
    code: 'GG',
    timezone: 'Europe/Guernsey',
  },
  {
    name: 'Guinea',
    dial_code: '+224',
    emoji: '🇬🇳',
    code: 'GN',
    timezone: 'Africa/Conakry',
  },
  {
    name: 'Guinea-Bissau',
    dial_code: '+245',
    emoji: '🇬🇼',
    code: 'GW',
    timezone: 'Africa/Bissau',
  },
  {
    name: 'Guyana',
    dial_code: '+595',
    emoji: '🇬🇾',
    code: 'GY',
    timezone: 'America/Guyana',
  },
  {
    name: 'Haiti',
    dial_code: '+509',
    emoji: '🇭🇹',
    code: 'HT',
    timezone: 'America/Port-au-Prince',
  },
  {
    name: 'Holy See (Vatican City State)',
    dial_code: '+379',
    emoji: '🇻🇦',
    code: 'VA',
    timezone: 'Europe/Vatican',
  },
  {
    name: 'Honduras',
    dial_code: '+504',
    emoji: '🇭🇳',
    code: 'HN',
    timezone: 'America/Tegucigalpa',
  },
  {
    name: 'Hong Kong',
    dial_code: '+852',
    emoji: '🇭🇰',
    code: 'HK',
    timezone: 'Asia/Hong_Kong',
  },
  {
    name: 'Hungary',
    dial_code: '+36',
    emoji: '🇭🇺',
    code: 'HU',
    timezone: 'Europe/Budapest',
  },
  {
    name: 'Iceland',
    dial_code: '+354',
    emoji: '🇮🇸',
    code: 'IS',
    timezone: 'Atlantic/Reykjavik',
  },
  {
    name: 'India',
    dial_code: '+91',
    emoji: '🇮🇳',
    code: 'IN',
    timezone: 'Asia/Kolkata',
  },
  {
    name: 'Indonesia',
    dial_code: '+62',
    emoji: '🇮🇩',
    code: 'ID',
    timezone: 'Asia/Jakarta',
  },
  {
    name: 'Iran, Islamic Republic of Persian Gulf',
    dial_code: '+98',
    emoji: '🇮🇷',
    code: 'IR',
    timezone: 'Asia/Tehran',
  },
  {
    name: 'Iraq',
    dial_code: '+964',
    emoji: '🇮🇷',
    code: 'IQ',
    timezone: 'Asia/Baghdad',
  },
  {
    name: 'Ireland',
    dial_code: '+353',
    emoji: '🇮🇪',
    code: 'IE',
    timezone: 'Europe/Dublin',
  },
  {
    name: 'Isle of Man',
    dial_code: '+44',
    emoji: '🇮🇲',
    code: 'IM',
    timezone: 'Europe/Isle_of_Man',
  },
  {
    name: 'Israel',
    dial_code: '+972',
    emoji: '🇮🇱',
    code: 'IL',
    timezone: 'Asia/Jerusalem',
  },
  {
    name: 'Italy',
    dial_code: '+39',
    emoji: '🇮🇹',
    code: 'IT',
    timezone: 'Europe/Rome',
  },
  {
    name: 'Jamaica',
    dial_code: '+1876',
    emoji: '🇯🇲',
    code: 'JM',
    timezone: 'America/Jamaica',
  },
  {
    name: 'Japan',
    dial_code: '+81',
    emoji: '🇯🇵',
    code: 'JP',
    timezone: 'Asia/Tokyo',
  },
  {
    name: 'Jersey',
    dial_code: '+44',
    emoji: '🇯🇪',
    code: 'JE',
    timezone: 'Europe/Jersey',
  },
  {
    name: 'Jordan',
    dial_code: '+962',
    emoji: '🇯🇴',
    code: 'JO',
    timezone: 'Asia/Amman',
  },
  {
    name: 'Kazakhstan',
    dial_code: '+77',
    emoji: '🇰🇿',
    code: 'KZ',
    timezone: 'Asia/Almaty',
  },
  {
    name: 'Kenya',
    dial_code: '+254',
    emoji: '🇰🇪',
    code: 'KE',
    timezone: 'Africa/Nairobi',
  },
  {
    name: 'Kiribati',
    dial_code: '+686',
    emoji: '🇰🇮',
    code: 'KI',
    timezone: 'Pacific/Tarawa',
  },
  {
    name: "Korea, Democratic People's Republic of Korea",
    dial_code: '+850',
    emoji: '🇰🇵',
    code: 'KP',
    timezone: 'Asia/Pyongyang',
  },
  {
    name: 'Korea, Republic of South Korea',
    dial_code: '+82',
    emoji: '🇰🇷',
    code: 'KR',
    timezone: 'Asia/Seoul',
  },
  {
    name: 'Kuwait',
    dial_code: '+965',
    emoji: '🇰🇼',
    code: 'KW',
    timezone: 'Asia/Kuwait',
  },
  {
    name: 'Kyrgyzstan',
    dial_code: '+996',
    emoji: '🇰🇬',
    code: 'KG',
    timezone: 'Asia/Bishkek',
  },
  {
    name: 'Laos',
    dial_code: '+856',
    emoji: '🇱🇦',
    code: 'LA',
    timezone: 'Asia/Vientiane',
  },
  {
    name: 'Latvia',
    dial_code: '+371',
    emoji: '🇱🇻',
    code: 'LV',
    timezone: 'Europe/Riga',
  },
  {
    name: 'Lebanon',
    dial_code: '+961',
    emoji: '🇱🇧',
    code: 'LB',
    timezone: 'Asia/Beirut',
  },
  {
    name: 'Lesotho',
    dial_code: '+266',
    emoji: '🇱🇸',
    code: 'LS',
    timezone: 'Africa/Maseru',
  },
  {
    name: 'Liberia',
    dial_code: '+231',
    emoji: '🇱🇷',
    code: 'LR',
    timezone: 'Africa/Monrovia',
  },
  {
    name: 'Libyan Arab Jamahiriya',
    dial_code: '+218',
    emoji: '🇱🇾',
    code: 'LY',
    timezone: 'Africa/Tripoli',
  },
  {
    name: 'Liechtenstein',
    dial_code: '+423',
    emoji: '🇱🇮',
    code: 'LI',
    timezone: 'Europe/Vaduz',
  },
  {
    name: 'Lithuania',
    dial_code: '+370',
    emoji: '🇱🇹',
    code: 'LT',
    timezone: 'Europe/Vilnius',
  },
  {
    name: 'Luxembourg',
    dial_code: '+352',
    emoji: '🇱🇺',
    code: 'LU',
    timezone: 'Europe/Luxembourg',
  },
  {
    name: 'Macao',
    dial_code: '+853',
    emoji: '🇲🇴',
    code: 'MO',
    timezone: 'Asia/Macau',
  },
  {
    name: 'Macedonia',
    dial_code: '+389',
    emoji: '🇲🇰',
    code: 'MK',
    timezone: 'Europe/Skopje',
  },
  {
    name: 'Madagascar',
    dial_code: '+261',
    emoji: '🇲🇬',
    code: 'MG',
    timezone: 'Indian/Antananarivo',
  },
  {
    name: 'Malawi',
    dial_code: '+265',
    emoji: '🇲🇼',
    code: 'MW',
    timezone: 'Africa/Blantyre',
  },
  {
    name: 'Malaysia',
    dial_code: '+60',
    emoji: '🇲🇾',
    code: 'MY',
    timezone: 'Asia/Kuala_Lumpur',
  },
  {
    name: 'Maldives',
    dial_code: '+960',
    emoji: '🇲🇻',
    code: 'MV',
    timezone: 'Indian/Maldives',
  },
  {
    name: 'Mali',
    dial_code: '+223',
    emoji: '🇲🇱',
    code: 'ML',
    timezone: 'Africa/Bamako',
  },
  {
    name: 'Malta',
    dial_code: '+356',
    emoji: '🇲🇹',
    code: 'MT',
    timezone: 'Europe/Malta',
  },
  {
    name: 'Marshall Islands',
    dial_code: '+692',
    emoji: '🇲🇭',
    code: 'MH',
    timezone: 'Pacific/Majuro',
  },
  {
    name: 'Martinique',
    dial_code: '+596',
    emoji: '🇲🇶',
    code: 'MQ',
    timezone: 'America/Martinique',
  },
  {
    name: 'Mauritania',
    dial_code: '+222',
    emoji: '🇲🇷',
    code: 'MR',
    timezone: 'Africa/Nouakchott',
  },
  {
    name: 'Mauritius',
    dial_code: '+230',
    emoji: '🇲🇺',
    code: 'MU',
    timezone: 'Indian/Mauritius',
  },
  {
    name: 'Mayotte',
    dial_code: '+262',
    emoji: '🇾🇹',
    code: 'YT',
    timezone: 'Indian/Mayotte',
  },
  {
    name: 'Mexico',
    dial_code: '+52',
    emoji: '🇲🇽',
    code: 'MX',
    timezone: 'America/Mexico_City',
  },
  {
    name: 'Micronesia, Federated States of Micronesia',
    dial_code: '+691',
    emoji: '🇫🇲',
    code: 'FM',
    timezone: 'Pacific/Chuuk',
  },
  {
    name: 'Moldova',
    dial_code: '+373',
    emoji: '🇲🇩',
    code: 'MD',
    timezone: 'Europe/Chisinau',
  },
  {
    name: 'Monaco',
    dial_code: '+377',
    emoji: '🇲🇨',
    code: 'MC',
    timezone: 'Europe/Monaco',
  },
  {
    name: 'Mongolia',
    dial_code: '+976',
    emoji: '🇲🇳',
    code: 'MN',
    timezone: 'Asia/Ulaanbaatar',
  },
  {
    name: 'Montenegro',
    dial_code: '+382',
    emoji: '🇲🇪',
    code: 'ME',
    timezone: 'Europe/Podgorica',
  },
  {
    name: 'Montserrat',
    dial_code: '+1664',
    emoji: '🇲🇸',
    code: 'MS',
    timezone: 'America/Montserrat',
  },
  {
    name: 'Morocco',
    dial_code: '+212',
    emoji: '🇲🇦',
    code: 'MA',
    timezone: 'Africa/Casablanca',
  },
  {
    name: 'Mozambique',
    dial_code: '+258',
    emoji: '🇲🇿',
    code: 'MZ',
    timezone: 'Africa/Maputo',
  },
  {
    name: 'Myanmar',
    dial_code: '+95',
    emoji: '🇲🇲',
    code: 'MM',
    timezone: 'Asia/Yangon',
  },
  {
    name: 'Namibia',
    emoji: '🇳🇦',
    dial_code: '+264',
    code: 'NA',
    timezone: 'Africa/Windhoek',
  },
  {
    name: 'Nauru',
    dial_code: '+674',
    emoji: '🇳🇷',
    code: 'NR',
    timezone: 'Pacific/Nauru',
  },
  {
    name: 'Nepal',
    dial_code: '+977',
    emoji: '🇳🇵',
    code: 'NP',
    timezone: 'Asia/Kathmandu',
  },
  {
    name: 'Netherlands',
    dial_code: '+31',
    emoji: '🇳🇱',
    code: 'NL',
    timezone: 'Europe/Amsterdam',
  },
  {
    name: 'Netherlands Antilles',
    dial_code: '+599',
    emoji: '🇧🇶',
    code: 'AN',
    timezone: 'America/Curacao',
  },
  {
    name: 'New Caledonia',
    dial_code: '+687',
    emoji: '🇳🇨',
    code: 'NC',
    timezone: 'Pacific/Noumea',
  },
  {
    name: 'New Zealand',
    dial_code: '+64',
    emoji: '🇳🇿',
    code: 'NZ',
    timezone: 'Pacific/Auckland',
  },
  {
    name: 'Nicaragua',
    dial_code: '+505',
    emoji: '🇳🇮',
    code: 'NI',
    timezone: 'America/Managua',
  },
  {
    name: 'Niger',
    dial_code: '+227',
    emoji: '🇳🇪',
    code: 'NE',
    timezone: 'Africa/Niamey',
  },
  {
    name: 'Nigeria',
    dial_code: '+234',
    emoji: '🇳🇬',
    code: 'NG',
    timezone: 'Africa/Lagos',
  },
  {
    name: 'Niue',
    dial_code: '+683',
    emoji: '🇳🇺',
    code: 'NU',
    timezone: 'Pacific/Niue',
  },
  {
    name: 'Norfolk Island',
    dial_code: '+672',
    emoji: '🇳🇫',
    code: 'NF',
    timezone: 'Pacific/Norfolk',
  },
  {
    name: 'Northern Mariana Islands',
    dial_code: '+1670',
    emoji: '🇲🇵',
    code: 'MP',
    timezone: 'Pacific/Saipan',
  },
  {
    name: 'Norway',
    dial_code: '+47',
    emoji: '🇳🇴',
    code: 'NO',
    timezone: 'Europe/Oslo',
  },
  {
    name: 'Oman',
    dial_code: '+968',
    emoji: '🇴🇲',
    code: 'OM',
    timezone: 'Asia/Muscat',
  },
  {
    name: 'Pakistan',
    dial_code: '+92',
    emoji: '🇵🇰',
    code: 'PK',
    timezone: 'Asia/Karachi',
  },
  {
    name: 'Palau',
    dial_code: '+680',
    emoji: '🇵🇼',
    code: 'PW',
    timezone: 'Pacific/Palau',
  },
  {
    name: 'Palestinian Territory, Occupied',
    dial_code: '+970',
    emoji: '🇵🇸',
    code: 'PS',
    timezone: 'Asia/Hebron',
  },
  {
    name: 'Panama',
    dial_code: '+507',
    emoji: '🇵🇦',
    code: 'PA',
    timezone: 'America/Panama',
  },
  {
    name: 'Papua New Guinea',
    dial_code: '+675',
    emoji: '🇵🇬',
    code: 'PG',
    timezone: 'Pacific/Port_Moresby',
  },
  {
    name: 'Paraguay',
    dial_code: '+595',
    emoji: '🇵🇾',
    code: 'PY',
    timezone: 'America/Asuncion',
  },
  {
    name: 'Peru',
    dial_code: '+51',
    emoji: '🇵🇪',
    code: 'PE',
    timezone: 'America/Lima',
  },
  {
    name: 'Philippines',
    dial_code: '+63',
    emoji: '🇵🇭',
    code: 'PH',
    timezone: 'Asia/Manila',
  },
  {
    name: 'Pitcairn',
    dial_code: '+872',
    emoji: '🇵🇳',
    code: 'PN',
    timezone: 'Pacific/Pitcairn',
  },
  {
    name: 'Poland',
    dial_code: '+48',
    emoji: '🇵🇱',
    code: 'PL',
    timezone: 'Europe/Warsaw',
  },
  {
    name: 'Portugal',
    dial_code: '+351',
    emoji: '🇵🇹',
    code: 'PT',
    timezone: 'Europe/Lisbon',
  },
  {
    name: 'Puerto Rico',
    dial_code: '+1939',
    emoji: '🇵🇷',
    code: 'PR',
    timezone: 'America/Puerto_Rico',
  },
  {
    name: 'Qatar',
    dial_code: '+974',
    emoji: '🇶🇦',
    code: 'QA',
    timezone: 'Asia/Qatar',
  },
  {
    name: 'Romania',
    dial_code: '+40',
    emoji: '🇷🇴',
    code: 'RO',
    timezone: 'Europe/Bucharest',
  },
  {
    name: 'Russia',
    dial_code: '+7',
    emoji: '🇷🇺',
    code: 'RU',
    timezone: 'Europe/Kaliningrad',
  },
  {
    name: 'Rwanda',
    dial_code: '+250',
    emoji: '🇷🇼',
    code: 'RW',
    timezone: 'Africa/Kigali',
  },
  {
    name: 'Reunion',
    dial_code: '+262',
    emoji: '🇷🇪',
    code: 'RE',
    timezone: 'Indian/Reunion',
  },
  {
    name: 'Saint Barthelemy',
    dial_code: '+590',
    emoji: '🇧🇱',
    code: 'BL',
    timezone: 'America/St_Barthelemy',
  },
  {
    name: 'Saint Helena, Ascension and Tristan Da Cunha',
    dial_code: '+290',
    emoji: '🇸🇭',
    code: 'SH',
    timezone: 'Atlantic/St_Helena',
  },
  {
    name: 'Saint Kitts and Nevis',
    dial_code: '+1869',
    emoji: '🇰🇳',
    code: 'KN',
    timezone: 'America/St_Kitts',
  },
  {
    name: 'Saint Lucia',
    dial_code: '+1758',
    emoji: '🇱🇨',
    code: 'LC',
    timezone: 'America/St_Lucia',
  },
  {
    name: 'Saint Martin',
    dial_code: '+590',
    emoji: '🇲🇫',
    code: 'MF',
    timezone: 'America/Marigot',
  },
  {
    name: 'Saint Pierre and Miquelon',
    dial_code: '+508',
    emoji: '🇵🇲',
    code: 'PM',
    timezone: 'America/Miquelon',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    dial_code: '+1784',
    emoji: '🇻🇨',
    code: 'VC',
    timezone: 'America/St_Vincent',
  },
  {
    name: 'Samoa',
    dial_code: '+685',
    emoji: '🇼🇸',
    code: 'WS',
    timezone: 'Pacific/Apia',
  },
  {
    name: 'San Marino',
    dial_code: '+378',
    emoji: '🇸🇲',
    code: 'SM',
    timezone: 'Europe/San_Marino',
  },
  {
    name: 'Sao Tome and Principe',
    dial_code: '+239',
    emoji: '🇸🇹',
    code: 'ST',
    timezone: 'Africa/Sao_Tome',
  },
  {
    name: 'Saudi Arabia',
    dial_code: '+966',
    emoji: '🇸🇦',
    code: 'SA',
    timezone: 'Asia/Riyadh',
  },
  {
    name: 'Senegal',
    dial_code: '+221',
    emoji: '🇸🇳',
    code: 'SN',
    timezone: 'Africa/Dakar',
  },
  {
    name: 'Serbia',
    dial_code: '+381',
    emoji: '🇷🇸',
    code: 'RS',
    timezone: 'Europe/Belgrade',
  },
  {
    name: 'Seychelles',
    dial_code: '+248',
    emoji: '🇸🇨',
    code: 'SC',
    timezone: 'Indian/Mahe',
  },
  {
    name: 'Sierra Leone',
    dial_code: '+232',
    emoji: '🇸🇱',
    code: 'SL',
    timezone: 'Africa/Freetown',
  },
  {
    name: 'Singapore',
    dial_code: '+65',
    emoji: '🇸🇬',
    code: 'SG',
    timezone: 'Asia/Singapore',
  },
  {
    name: 'Slovakia',
    dial_code: '+421',
    emoji: '🇸🇰',
    code: 'SK',
    timezone: 'Europe/Bratislava',
  },
  {
    name: 'Slovenia',
    dial_code: '+386',
    emoji: '🇸🇮',
    code: 'SI',
    timezone: 'Europe/Ljubljana',
  },
  {
    name: 'Solomon Islands',
    dial_code: '+677',
    emoji: '🇸🇧',
    code: 'SB',
    timezone: 'Pacific/Guadalcanal',
  },
  {
    name: 'Somalia',
    dial_code: '+252',
    emoji: '🇸🇴',
    code: 'SO',
    timezone: 'Africa/Mogadishu',
  },
  {
    name: 'South Africa',
    dial_code: '+27',
    emoji: '🇿🇦',
    code: 'ZA',
    timezone: 'Africa/Johannesburg',
  },
  {
    name: 'South Sudan',
    dial_code: '+211',
    emoji: '🇸🇸',
    code: 'SS',
    timezone: 'Africa/Juba',
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    dial_code: '+500',
    emoji: '🇬🇸',
    code: 'GS',
    timezone: 'Atlantic/South_Georgia',
  },
  {
    name: 'Spain',
    dial_code: '+34',
    emoji: '🇪🇸',
    code: 'ES',
    timezone: 'Europe/Madrid',
  },
  {
    name: 'Sri Lanka',
    dial_code: '+94',
    emoji: '🇱🇰',
    code: 'LK',
    timezone: 'Asia/Colombo',
  },
  {
    name: 'Sudan',
    dial_code: '+249',
    emoji: '🇸🇩',
    code: 'SD',
    timezone: 'Africa/Khartoum',
  },
  {
    name: 'Suriname',
    dial_code: '+597',
    emoji: '🇸🇷',
    code: 'SR',
    timezone: 'America/Paramaribo',
  },
  {
    name: 'Svalbard and Jan Mayen',
    dial_code: '+47',
    emoji: '🇸🇯',
    code: 'SJ',
    timezone: 'Arctic/Longyearbyen',
  },
  {
    name: 'Swaziland',
    dial_code: '+268',
    emoji: '🇸🇿',
    code: 'SZ',
    timezone: 'Africa/Mbabane',
  },
  {
    name: 'Sweden',
    dial_code: '+46',
    emoji: '🇸🇪',
    code: 'SE',
    timezone: 'Europe/Stockholm',
  },
  {
    name: 'Switzerland',
    dial_code: '+41',
    emoji: '🇨🇭',
    code: 'CH',
    timezone: 'Europe/Zurich',
  },
  {
    name: 'Syrian Arab Republic',
    dial_code: '+963',
    emoji: '🇸🇾',
    code: 'SY',
    timezone: 'Asia/Damascus',
  },
  {
    name: 'Taiwan',
    dial_code: '+886',
    emoji: '🇹🇼',
    code: 'TW',
    timezone: 'Asia/Taipei',
  },
  {
    name: 'Tajikistan',
    dial_code: '+992',
    emoji: '🇹🇯',
    code: 'TJ',
    timezone: 'Asia/Dushanbe',
  },
  {
    name: 'Tanzania, United Republic of Tanzania',
    dial_code: '+255',
    emoji: '🇹🇿',
    code: 'TZ',
    timezone: 'Africa/Dar_es_Salaam',
  },
  {
    name: 'Thailand',
    dial_code: '+66',
    emoji: '🇹🇭',
    code: 'TH',
    timezone: 'Asia/Bangkok',
  },
  {
    name: 'Timor-Leste',
    dial_code: '+670',
    emoji: '🇹🇱',
    code: 'TL',
    timezone: 'Asia/Dili',
  },
  {
    name: 'Togo',
    dial_code: '+228',
    emoji: '🇹🇬',
    code: 'TG',
    timezone: 'Africa/Lome',
  },
  {
    name: 'Tokelau',
    dial_code: '+690',
    emoji: '🇹🇰',
    code: 'TK',
    timezone: 'Pacific/Fakaofo',
  },
  {
    name: 'Tonga',
    dial_code: '+676',
    emoji: '🇹🇴',
    code: 'TO',
    timezone: 'Pacific/Tongatapu',
  },
  {
    name: 'Trinidad and Tobago',
    dial_code: '+1868',
    emoji: '🇹🇹',
    code: 'TT',
    timezone: 'America/Port_of_Spain',
  },
  {
    name: 'Tunisia',
    dial_code: '+216',
    emoji: '🇹🇳',
    code: 'TN',
    timezone: 'Africa/Tunis',
  },
  {
    name: 'Turkey',
    dial_code: '+90',
    emoji: '🇹🇷',
    code: 'TR',
    timezone: 'Europe/Istanbul',
  },
  {
    name: 'Turkmenistan',
    dial_code: '+993',
    emoji: '🇹🇲',
    code: 'TM',
    timezone: 'Asia/Ashgabat',
  },
  {
    name: 'Turks and Caicos Islands',
    dial_code: '+1649',
    emoji: '🇹🇨',
    code: 'TC',
    timezone: 'America/Grand_Turk',
  },
  {
    name: 'Tuvalu',
    dial_code: '+688',
    emoji: '🇹🇻',
    code: 'TV',
    timezone: 'Pacific/Funafuti',
  },
  {
    name: 'Uganda',
    dial_code: '+256',
    emoji: '🇺🇬',
    code: 'UG',
    timezone: 'Africa/Kampala',
  },
  {
    name: 'Ukraine',
    dial_code: '+380',
    emoji: '🇺🇦',
    code: 'UA',
    timezone: 'Europe/Kiev',
  },
  {
    name: 'United Arab Emirates',
    dial_code: '+971',
    emoji: '🇦🇪',
    code: 'AE',
    timezone: 'Asia/Dubai',
  },
  {
    name: 'United Kingdom',
    dial_code: '+44',
    emoji: '🇬🇧',
    code: 'GB',
    timezone: 'Europe/London',
  },
  {
    name: 'United States',
    dial_code: '+1',
    emoji: '🇺🇸',
    code: 'US',
    timezone: 'America/New_York',
  },
  {
    name: 'Uruguay',
    dial_code: '+598',
    emoji: '🇺🇾',
    code: 'UY',
    timezone: 'America/Montevideo',
  },
  {
    name: 'Uzbekistan',
    dial_code: '+998',
    emoji: '🇺🇿',
    code: 'UZ',
    timezone: 'Asia/Samarkand',
  },
  {
    name: 'Vanuatu',
    dial_code: '+678',
    emoji: '🇻🇺',
    code: 'VU',
    timezone: 'Pacific/Efate',
  },
  {
    name: 'Venezuela, Bolivarian Republic of Venezuela',
    dial_code: '+58',
    emoji: '🇻🇪',
    code: 'VE',
    timezone: 'America/Caracas',
  },
  {
    name: 'Vietnam',
    dial_code: '+84',
    emoji: '🇻🇳',
    code: 'VN',
    timezone: 'Asia/Ho_Chi_Minh',
  },
  {
    name: 'Virgin Islands, British',
    dial_code: '+1284',
    emoji: '🇻🇬',
    code: 'VG',
    timezone: 'America/Tortola',
  },
  {
    name: 'Virgin Islands, U.S.',
    dial_code: '+1340',
    emoji: '🇻🇮',
    code: 'VI',
    timezone: 'America/St_Thomas',
  },
  {
    name: 'Wallis and Futuna',
    dial_code: '+681',
    emoji: '🇼🇫',
    code: 'WF',
    timezone: 'Pacific/Wallis',
  },
  {
    name: 'Yemen',
    dial_code: '+967',
    emoji: '🇾🇪',
    code: 'YE',
    timezone: 'Asia/Aden',
  },
  {
    name: 'Zambia',
    dial_code: '+260',
    emoji: '🇿🇲',
    code: 'ZM',
    timezone: 'Africa/Lusaka',
  },
  {
    name: 'Zimbabwe',
    dial_code: '+263',
    emoji: '🇿🇼',
    code: 'ZW',
    timezone: 'Africa/Harare',
  },
];
