import { MigrationInterface, QueryRunner } from "typeorm";

export class Initial1710409799451 implements MigrationInterface {
    name = 'Initial1710409799451'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "client_persona" ("id" SERIAL NOT NULL, "clientPersonaId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "PK_cf22829c21cc59fe0406b03f97d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contract_awarder_persona" ("id" SERIAL NOT NULL, "contractAwarderPersonaId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "PK_4d4c58fe048b0d2751c97ab4259" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "factor_persona" ("id" SERIAL NOT NULL, "factorPersonaId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "PK_8b63b9be0639d338c7ded997070" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."OrganizationPersonRoleEnum" AS ENUM('RELATIONSHIP_MANAGER')`);
        await queryRunner.query(`CREATE TABLE "organization_person_role" ("id" SERIAL NOT NULL, "role" "public"."OrganizationPersonRoleEnum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "organizationPersonId" integer, CONSTRAINT "PK_da94429a071bddc2efd2357544b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "organization_person" ("id" SERIAL NOT NULL, "designation" character varying, "sub" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "organizationId" integer, "personId" integer, CONSTRAINT "PK_e94553ff34338a3882ed305a74d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "supplier_persona" ("id" SERIAL NOT NULL, "supplierPersonaId" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "PK_6c6dcbb97bce450fbaae2e04caf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."CountryCodeEnum" AS ENUM('AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AO', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AW', 'AX', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BL', 'BM', 'BN', 'BO', 'BQ', 'BR', 'BS', 'BT', 'BV', 'BW', 'BY', 'BZ', 'CA', 'CC', 'CD', 'CF', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN', 'CO', 'CR', 'CU', 'CV', 'CW', 'CX', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'EH', 'ER', 'ES', 'ET', 'FI', 'FJ', 'FK', 'FM', 'FO', 'FR', 'GA', 'GB', 'GD', 'GE', 'GF', 'GG', 'GH', 'GI', 'GL', 'GM', 'GN', 'GP', 'GQ', 'GR', 'GS', 'GT', 'GU', 'GW', 'GY', 'HK', 'HM', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IM', 'IN', 'IO', 'IQ', 'IR', 'IS', 'IT', 'JE', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KP', 'KR', 'KW', 'KY', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MC', 'MD', 'ME', 'MF', 'MG', 'MH', 'MK', 'ML', 'MM', 'MN', 'MO', 'MP', 'MQ', 'MR', 'MS', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NC', 'NE', 'NF', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NU', 'NZ', 'OM', 'PA', 'PE', 'PF', 'PG', 'PH', 'PK', 'PL', 'PM', 'PN', 'PR', 'PS', 'PT', 'PW', 'PY', 'QA', 'RE', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE', 'SG', 'SH', 'SI', 'SJ', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'SS', 'ST', 'SV', 'SX', 'SY', 'SZ', 'TC', 'TD', 'TF', 'TG', 'TH', 'TJ', 'TK', 'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'UM', 'US', 'UY', 'UZ', 'VA', 'VC', 'VE', 'VG', 'VI', 'VN', 'VU', 'WF', 'WS', 'YE', 'YT', 'ZA', 'ZM', 'ZW')`);
        await queryRunner.query(`CREATE TYPE "public"."OrganizationTypeEnum" AS ENUM('GOVERNMENT_EP', 'GOVERNMENT_NON_EP', 'GOVERNMENT_LINKED_COMPANY', 'MULTI_NATIONAL_COMPANY', 'PRIVATE_COMPANY', 'OTHERS')`);
        await queryRunner.query(`CREATE TYPE "public"."OrganizationBusinessSectorEnum" AS ENUM('SUPPLY', 'SERVICES', 'SUPPLY_AND_SERVICES', 'RETAIL', 'WHOLESALE', 'MANUFACTURING', 'CONSTRUCTION', 'INFORMATION_AND_COMMUNICATION', 'OTHERS')`);
        await queryRunner.query(`CREATE TYPE "public"."OrganizationNatureOfBusinessEnum" AS ENUM('AGRICULTURE', 'AUTOMOBILE', 'AVIATION', 'BUSINESS_SERVICES', 'COMMUNICATION_AND_DIGITAL', 'CONSTRUCTION', 'DEFENCE', 'EDUCATION', 'ENERGY', 'ENTREPRENEUR_AND_COOPERATIVE_DEVELOPMENT', 'ENVIRONMENT_AND_SUSTAINABILITY', 'FINANCE', 'HEALTHCARE', 'HOME_AFFAIRS', 'HOSPITALITY_AND_TOURISM')`);
        await queryRunner.query(`CREATE TABLE "organization" ("id" SERIAL NOT NULL, "organizationName" character varying NOT NULL, "alias" character varying, "country" "public"."CountryCodeEnum" NOT NULL DEFAULT 'MY', "organizationType" "public"."OrganizationTypeEnum", "organizationTypeOther" character varying, "businessRegistrationNumber" character varying, "taxIdentificationNumber" character varying, "sstRegistrationNumber" character varying, "businessSector" "public"."OrganizationBusinessSectorEnum", "natureOfBusiness" "public"."OrganizationNatureOfBusinessEnum", "coreBusiness" character varying, "incorporationDate" TIMESTAMP, "operationStartDate" TIMESTAMP, "businessAddress" character varying, "registeredAddress" character varying, "factoryAddress" character varying, "organizationWebsite" character varying, "organizationLogo" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "clientPersonaId" integer, "contractAwarderPersonaId" integer, "supplierPersonaId" integer, "factorPersonaId" integer, CONSTRAINT "REL_3f4e5bd04e9e027d9d2a309af4" UNIQUE ("clientPersonaId"), CONSTRAINT "REL_cf61bbd853fe6993f77cb42d0c" UNIQUE ("contractAwarderPersonaId"), CONSTRAINT "REL_b30003a54d14f4433a2ac455df" UNIQUE ("supplierPersonaId"), CONSTRAINT "REL_d3a0a571f2b00f3542be387048" UNIQUE ("factorPersonaId"), CONSTRAINT "PK_472c1f99a32def1b0abb219cd67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."BankProviderEnum" AS ENUM('MAYBANK', 'CIMB', 'PUBLIC_BANK', 'RHB', 'HONG_LEONG_BANK', 'AMBANK', 'UOB', 'BANK_RAKYAT', 'OCBC', 'HSBC', 'BANK_ISLAM', 'AFFIN_BANK', 'ALLIANCE_BANK', 'STANDARD_CHARTERED', 'CITIBANK')`);
        await queryRunner.query(`CREATE TYPE "public"."BankAccountTypeEnum" AS ENUM('CURRENT_ACCOUNT', 'SAVINGS_ACCOUNT', 'MULTI_CURRENCY_ACCOUNT', 'FIXED_DEPOSIT_ACCOUNT')`);
        await queryRunner.query(`CREATE TYPE "public"."CurrencyCodeEnum" AS ENUM('USD', 'CAD', 'EUR', 'AED', 'AFN', 'ALL', 'AMD', 'ARS', 'AUD', 'AZN', 'BAM', 'BDT', 'BGN', 'BHD', 'BIF', 'BND', 'BOB', 'BRL', 'BWP', 'BYN', 'BZD', 'CDF', 'CHF', 'CLP', 'CNY', 'COP', 'CRC', 'CVE', 'CZK', 'DJF', 'DKK', 'DOP', 'DZD', 'EEK', 'EGP', 'ERN', 'ETB', 'GBP', 'GEL', 'GHS', 'GNF', 'GTQ', 'HKD', 'HNL', 'HRK', 'HUF', 'IDR', 'ILS', 'INR', 'IQD', 'IRR', 'ISK', 'JMD', 'JOD', 'JPY', 'KES', 'KHR', 'KMF', 'KRW', 'KWD', 'KZT', 'LBP', 'LKR', 'LTL', 'LVL', 'LYD', 'MAD', 'MDL', 'MGA', 'MKD', 'MMK', 'MOP', 'MUR', 'MXN', 'MYR', 'MZN', 'NAD', 'NGN', 'NIO', 'NOK', 'NPR', 'NZD', 'OMR', 'PAB', 'PEN', 'PHP', 'PKR', 'PLN', 'PYG', 'QAR', 'RON', 'RSD', 'RUB', 'RWF', 'SAR', 'SDG', 'SEK', 'SGD', 'SOS', 'SYP', 'THB', 'TND', 'TOP', 'TRY', 'TTD', 'TWD', 'TZS', 'UAH', 'UGX', 'UYU', 'UZS', 'VEF', 'VND', 'XAF', 'XOF', 'YER', 'ZAR', 'ZMK', 'ZWL')`);
        await queryRunner.query(`CREATE TABLE "bank_account" ("id" SERIAL NOT NULL, "bankProvider" "public"."BankProviderEnum" NOT NULL, "accountHolderName" character varying NOT NULL, "branchName" character varying, "bankAddress" character varying, "bankAccountNumber" character varying NOT NULL, "swiftCode" character varying, "branchCode" character varying, "bankAccountType" "public"."BankAccountTypeEnum", "currency" "public"."CurrencyCodeEnum" NOT NULL DEFAULT 'MYR', "onlineBankAvailable" boolean NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "organizationId" integer, "personId" integer, CONSTRAINT "PK_f3246deb6b79123482c6adb9745" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "person" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "preferredUsername" character varying, "residentialAddress" character varying, "identificationNumber" character varying, "mobileNumber" character varying, "email" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "PK_5fdaf670315c4b7e70cce85daa3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."PersonSupportingDocumentTypeEnum" AS ENUM('NRIC')`);
        await queryRunner.query(`CREATE TABLE "person_supporting_document" ("id" SERIAL NOT NULL, "bucketKey" character varying NOT NULL, "supportingDocumentType" "public"."PersonSupportingDocumentTypeEnum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "personId" integer, CONSTRAINT "PK_8ea25e01a217220809a521cb188" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "organization_person_role" ADD CONSTRAINT "FK_437efe57af5d6fee20387c5714c" FOREIGN KEY ("organizationPersonId") REFERENCES "organization_person"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_person" ADD CONSTRAINT "FK_52119a73304c90a220f1f609f27" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization_person" ADD CONSTRAINT "FK_fe6d15893551339be24e742674c" FOREIGN KEY ("personId") REFERENCES "person"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_3f4e5bd04e9e027d9d2a309af4c" FOREIGN KEY ("clientPersonaId") REFERENCES "client_persona"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_cf61bbd853fe6993f77cb42d0cc" FOREIGN KEY ("contractAwarderPersonaId") REFERENCES "contract_awarder_persona"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_b30003a54d14f4433a2ac455df4" FOREIGN KEY ("supplierPersonaId") REFERENCES "supplier_persona"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "organization" ADD CONSTRAINT "FK_d3a0a571f2b00f3542be3870482" FOREIGN KEY ("factorPersonaId") REFERENCES "factor_persona"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bank_account" ADD CONSTRAINT "FK_7cc1c14d5b053dc9effa23a1f24" FOREIGN KEY ("organizationId") REFERENCES "organization"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bank_account" ADD CONSTRAINT "FK_d93e5de082b6eb0b3249d64db1a" FOREIGN KEY ("personId") REFERENCES "person"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "person_supporting_document" ADD CONSTRAINT "FK_7efb3c80985977ee76cba69b431" FOREIGN KEY ("personId") REFERENCES "person"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "person_supporting_document" DROP CONSTRAINT "FK_7efb3c80985977ee76cba69b431"`);
        await queryRunner.query(`ALTER TABLE "bank_account" DROP CONSTRAINT "FK_d93e5de082b6eb0b3249d64db1a"`);
        await queryRunner.query(`ALTER TABLE "bank_account" DROP CONSTRAINT "FK_7cc1c14d5b053dc9effa23a1f24"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_d3a0a571f2b00f3542be3870482"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_b30003a54d14f4433a2ac455df4"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_cf61bbd853fe6993f77cb42d0cc"`);
        await queryRunner.query(`ALTER TABLE "organization" DROP CONSTRAINT "FK_3f4e5bd04e9e027d9d2a309af4c"`);
        await queryRunner.query(`ALTER TABLE "organization_person" DROP CONSTRAINT "FK_fe6d15893551339be24e742674c"`);
        await queryRunner.query(`ALTER TABLE "organization_person" DROP CONSTRAINT "FK_52119a73304c90a220f1f609f27"`);
        await queryRunner.query(`ALTER TABLE "organization_person_role" DROP CONSTRAINT "FK_437efe57af5d6fee20387c5714c"`);
        await queryRunner.query(`DROP TABLE "person_supporting_document"`);
        await queryRunner.query(`DROP TYPE "public"."PersonSupportingDocumentTypeEnum"`);
        await queryRunner.query(`DROP TABLE "person"`);
        await queryRunner.query(`DROP TABLE "bank_account"`);
        await queryRunner.query(`DROP TYPE "public"."CurrencyCodeEnum"`);
        await queryRunner.query(`DROP TYPE "public"."BankAccountTypeEnum"`);
        await queryRunner.query(`DROP TYPE "public"."BankProviderEnum"`);
        await queryRunner.query(`DROP TABLE "organization"`);
        await queryRunner.query(`DROP TYPE "public"."OrganizationNatureOfBusinessEnum"`);
        await queryRunner.query(`DROP TYPE "public"."OrganizationBusinessSectorEnum"`);
        await queryRunner.query(`DROP TYPE "public"."OrganizationTypeEnum"`);
        await queryRunner.query(`DROP TYPE "public"."CountryCodeEnum"`);
        await queryRunner.query(`DROP TABLE "supplier_persona"`);
        await queryRunner.query(`DROP TABLE "organization_person"`);
        await queryRunner.query(`DROP TABLE "organization_person_role"`);
        await queryRunner.query(`DROP TYPE "public"."OrganizationPersonRoleEnum"`);
        await queryRunner.query(`DROP TABLE "factor_persona"`);
        await queryRunner.query(`DROP TABLE "contract_awarder_persona"`);
        await queryRunner.query(`DROP TABLE "client_persona"`);
    }

}
