import { MigrationInterface, QueryRunner } from "typeorm";

export class AddRiskScoringTables1782282156797 implements MigrationInterface {
    name = 'AddRiskScoringTables1782282156797'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP CONSTRAINT "FK_20c4be58213e8af3ba5b2ad49e0"`);
        await queryRunner.query(`CREATE TYPE "public"."FinancialCreditReportTypeEnum" AS ENUM('YEAR_END')`);
        await queryRunner.query(`CREATE TABLE "financial_credit_report" ("id" SERIAL NOT NULL, "organization_id" integer NOT NULL, "organization_name" character varying NOT NULL, "supporting_document_id" integer, "report_date" TIMESTAMP, "report_year" integer, "report_type" "public"."FinancialCreditReportTypeEnum" NOT NULL DEFAULT 'YEAR_END', "years_of_operation" integer NOT NULL, "profitability" character varying(3), "current_ratio" numeric, "total_liabilities" numeric, "total_revenue" numeric, "net_revenue" numeric, "net_profit" numeric, "total_current_liabilities" numeric, "loan_to_receivable" numeric, "total_loan" numeric, "total_current_assets" numeric, "total_capital" numeric, "net_debt" numeric, "total_equity" numeric, "total_debt" numeric, "account_receivables" numeric, "ebitda" numeric, "total_equity_and_liabilities" numeric, "debt_to_equity" numeric, "debt_to_ebitda" numeric, "debt_to_capital" numeric, "interest_expense" numeric, "depreciation_and_amortization" numeric, "retained_cash_flow" numeric, "rcf_to_net_debt" numeric, "ebitda_to_interest_expense" numeric, "principal_repayment" numeric, "debt_service_coverage_ratio" numeric, "created_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "PK_92bd75d211df66889c6ed809a92" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_80c1401c52215af0630e72091c" ON "financial_credit_report" ("organization_id") `);
        await queryRunner.query(`CREATE TABLE "risk_high_classification_scoring" ("id" SERIAL NOT NULL, "riskApplicationScoringId" integer NOT NULL, "riskHighClassificationFactorId" integer NOT NULL, "isSelected" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "PK_49d12dc02ff9cba2387d4c0314e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "risk_high_classification_factor" ("id" SERIAL NOT NULL, "riskModelId" integer, "riskFactor" character varying NOT NULL, "description" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "PK_97eb5e4c01a9a335aa493ba4dc9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "risk_factor_scoring" ("id" SERIAL NOT NULL, "riskApplicationScoringId" integer NOT NULL, "riskFactorId" integer NOT NULL, "selectedEvaluationParamId" integer, "riskFactorName" character varying, "parentId" integer, "selectedCountry" character varying, "score" numeric, "weight" numeric, "scoreRangeMax" integer, "scoreRangeMin" integer, "isAQuestion" integer, "totalSubFactorScore" numeric, "factorScore" double precision, "weightedFactorScore" double precision, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "PK_012606fd48eb95c60de9a35e3f2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."RiskCategoryEnum_RiskEvaluationParam" AS ENUM('LOW', 'MEDIUM', 'HIGH')`);
        await queryRunner.query(`CREATE TYPE "public"."RiskEvalScoreTypeEnum" AS ENUM('FIXED', 'RANGE')`);
        await queryRunner.query(`CREATE TABLE "risk_evaluation_parameter" ("id" SERIAL NOT NULL, "riskFactorId" integer, "parentId" integer, "name" character varying NOT NULL, "description" character varying, "weight" numeric, "riskCategory" "public"."RiskCategoryEnum_RiskEvaluationParam", "scoreType" "public"."RiskEvalScoreTypeEnum", "fixedScore" integer, "scoreRangeMin" integer, "scoreRangeMax" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "PK_d93d4f22b9ab8e144cd97ffe1c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."RiskFactorScoreMethodEnum" AS ENUM('NUMERIC_SCORING', 'LABEL_SELECTION', 'COUNTRY_SELECTION', 'DROPDOWN_SELECTION')`);
        await queryRunner.query(`CREATE TABLE "risk_factor" ("id" SERIAL NOT NULL, "riskModelId" integer, "parentId" integer, "riskFactorName" character varying NOT NULL, "description" character varying, "weight" numeric, "isSetAsCategory" integer NOT NULL DEFAULT '0', "hasSubFactor" integer NOT NULL DEFAULT '0', "tabName" character varying, "scoreMethod" "public"."RiskFactorScoreMethodEnum", "isRequireEvaluationParameter" integer NOT NULL DEFAULT '0', "scoreRangeMin" integer, "scoreRangeMax" integer, "countryList" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "PK_c8cba10b14fd3d239a3c9243643" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."RiskModelStatusEnum" AS ENUM('PUBLISHED', 'DRAFT', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TABLE "risk_model" ("id" SERIAL NOT NULL, "riskModelStatus" "public"."RiskModelStatusEnum" NOT NULL, "riskModelNumber" character varying NOT NULL, "riskModelName" character varying NOT NULL, "description" character varying, "numberOfActiveProfiles" integer NOT NULL DEFAULT '0', "lowRiskThresholds" numrange NOT NULL, "mediumRiskThresholds" numrange NOT NULL, "highRiskThresholds" numrange NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "UQ_3109a9d6d1311e1d26aa6dd55d0" UNIQUE ("riskModelNumber"), CONSTRAINT "UQ_54adefb1d77bd613701e1e682e2" UNIQUE ("riskModelName"), CONSTRAINT "PK_0e2e504e78eaadd5fdc47c5b7ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."RiskApplicationAuditActionEnum" AS ENUM('MANUAL_REVIEW_STARTED', 'MANUAL_REVIEW_APPROVED', 'MANUAL_REVIEW_REJECTED', 'SCORE_RECALCULATED', 'PROFILE_ASSIGNED')`);
        await queryRunner.query(`CREATE TABLE "risk_application_audit_log" ("id" SERIAL NOT NULL, "risk_application_scoring_id" integer NOT NULL, "action_type" "public"."RiskApplicationAuditActionEnum" NOT NULL, "performed_by" character varying NOT NULL, "details" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "PK_e232d89a30effa86eb476da5f8d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "risk_manual_review_alert" ("id" SERIAL NOT NULL, "risk_application_scoring_id" integer NOT NULL, "quantitative_parameter_id" integer, "quantitative_sub_parameter_id" integer, "threshold_rule_id" integer, "actual_value_numeric" numeric, "actual_value_label" character varying, "message" character varying, "is_resolved" integer NOT NULL DEFAULT '0', "is_resolved_by" character varying, "is_resolved_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_787955898ce91732b5fffe3b21e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."RiskCategoryEnum_Filter1" AS ENUM('LOW', 'MEDIUM', 'HIGH')`);
        await queryRunner.query(`CREATE TYPE "public"."RiskFilter1StatusEnum" AS ENUM('APPROVED', 'REJECTED', 'PENDING_MANUAL_REVIEW')`);
        await queryRunner.query(`CREATE TYPE "public"."RiskCategoryEnum_Filter2" AS ENUM('LOW', 'MEDIUM', 'HIGH')`);
        await queryRunner.query(`CREATE TABLE "risk_application_scoring" ("id" SERIAL NOT NULL, "applicationId" integer, "risk_profile_id" integer, "riskModelId" integer, "isRiskSurveyCompleted" integer, "risk_filter_1_total_score" numeric, "risk_filter_1_category" "public"."RiskCategoryEnum_Filter1", "risk_filter_1_status" "public"."RiskFilter1StatusEnum", "risk_filter_1_updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "risk_filter_2_total_score" numeric, "risk_filter_2_category" "public"."RiskCategoryEnum_Filter2", "risk_filter_2_updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "isSubmittedForSettlement" integer, "isAuthorizationRequired" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "REL_af2c45573a4e901a7cd84aa235" UNIQUE ("applicationId"), CONSTRAINT "PK_96f3b65e51bb3d0722b7d9a8eef" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "risk_quantitative_profile_scoring" ("id" SERIAL NOT NULL, "risk_application_scoring_id" integer NOT NULL, "quantitative_parameter_id" integer NOT NULL, "quantitative_parameter_name" character varying NOT NULL, "quantitative_sub_parameter_id" integer, "quantitative_sub_parameter_name" character varying, "threshold_rule_id" integer, "value_numeric" numeric, "value_label" character varying, "weight" numeric NOT NULL, "score" numeric, "weighted_score" numeric, "created_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "PK_eb6e001a0fbab6623e654e47b48" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ThresholdBreachTriggerComparisonOperatorEnum" AS ENUM('=', '>', '>=', '<', '<=')`);
        await queryRunner.query(`CREATE TABLE "risk_quantitative_threshold_rule" ("id" SERIAL NOT NULL, "risk_profile_id" integer NOT NULL, "quantitative_parameter_id" integer NOT NULL, "quantitative_sub_parameter_id" integer NOT NULL, "score" numeric, "threshold_value" numeric, "threshold_label" character varying, "comparison_operator" "public"."ThresholdBreachTriggerComparisonOperatorEnum" NOT NULL, "is_manual_trigger_allowed" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "PK_dd9a50310a090fa770c288a7a6d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."BusinessSectorEnum" AS ENUM('AGRICULTURE_AND_FORESTRY', 'AUTOMOTIVE', 'BANKING_AND_FINANCIAL_SERVICES', 'BIOTECHNOLOGY', 'CHEMICALS', 'CONSTRUCTION_AND_REAL_ESTATE', 'CONSUMER_GOODS', 'EDUCATION_AND_TRAINING', 'ENERGY', 'ENTERTAINMENT_AND_MEDIA', 'ENVIRONMENTAL_SERVICES', 'FASHION_AND_APPAREL', 'FOOD_AND_BEVERAGE', 'HEALTHCARE_AND_PHARMACEUTICALS', 'HOSPITALITY_AND_TRAVEL', 'INFORMATION_TECHNOLOGY', 'INSURANCE', 'LEGAL_SERVICES', 'LOGISTICS_AND_TRANSPORTATION', 'MANUFACTURING', 'MARKETING_AND_ADVERTISING', 'MINING_AND_METALS', 'NON_PROFIT_AND_NGOS', 'PUBLIC_SECTOR_AND_GOVERNMENT', 'RETAIL_AND_WHOLESALE', 'TELECOMMUNICATIONS', 'TEXTILES', 'UTILITIES', 'WHOLESALE_TRADE', 'OTHERS')`);
        await queryRunner.query(`CREATE TABLE "risk_profile" ("id" SERIAL NOT NULL, "risk_profile_code" character varying NOT NULL, "business_sector" "public"."BusinessSectorEnum", "business_sector_other" character varying, "capital_size" character varying, "capital_currency" "public"."CurrencyCodeEnum", "is_default" integer NOT NULL, "number_of_active_profiles" integer NOT NULL DEFAULT '0', "low_risk_thresholds" numrange NOT NULL, "medium_risk_thresholds" numrange NOT NULL, "high_risk_thresholds" numrange NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "UQ_bf83d3b8d80e56b9cb6878033d1" UNIQUE ("risk_profile_code"), CONSTRAINT "PK_f1a916f12099696a7295531ed9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "risk_quantitative_profile_weight" ("id" SERIAL NOT NULL, "risk_profile_id" integer NOT NULL, "quantitative_parameter_id" integer NOT NULL, "quantitative_sub_parameter_id" integer, "weight" numeric NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_83abb675176445ae1900d549cf9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "risk_quantitative_sub_parameter" ("id" SERIAL NOT NULL, "quantitative_parameter_id" integer NOT NULL, "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "PK_2e9bcc1a75111b313c6e0303378" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "risk_quantitative_parameter" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, "updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone, CONSTRAINT "PK_ab2d75fc580c124db0694397c3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "bucketKey"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "supportingDocumentType"`);
        await queryRunner.query(`DROP TYPE "public"."ApplicationSupportingDocumentTypeEnum"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "fileExtension"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "isActive"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "applicationId"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "isVerified"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "application_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "file_name" character varying`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "file_extension" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."ApplicationSupportingDocumentTypeEnum" AS ENUM('LETTER_OF_AWARD', 'PURCHASE_ORDER', 'CONTRACT', 'MISSING_PAGES', 'CASH_FLOW_APPENDED', 'APPENDIX_IN_CONTRACT', 'RELATED_COMPANY_NOTES', 'BANK_STATEMENT', 'FINANCIAL_STATEMENT', 'COMPANY_PROFILE', 'COMPANY_GROUP_STRUCTURE', 'ORGANIZATION_CHART', 'CREDIT_CONSENT_FORM', 'SITE_VISIT_REPORT')`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "supporting_document_type" "public"."ApplicationSupportingDocumentTypeEnum"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "bucket_key" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "is_verified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "is_active" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "created_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "updated_at" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone`);
        await queryRunner.query(`ALTER TABLE "application" ADD "applicationNumber" character varying`);
        await queryRunner.query(`ALTER TABLE "application" ADD CONSTRAINT "UQ_b1d358131fef2ce43b4176f3b06" UNIQUE ("applicationNumber")`);
        await queryRunner.query(`ALTER TYPE "public"."ApplicationStatusEnum" RENAME TO "ApplicationStatusEnum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."ApplicationStatusEnum" AS ENUM('DRAFT', 'PENDING_EXPERIAN_CONSENT', 'PENDING_EXPERIAN_REPORT', 'PENDING_CLIENT_SUBMISSION', 'PENDING_ASSIGNEE_REVIEW', 'PENDING_RISK_FILTER_1', 'PENDING_RISK_FILTER_2')`);
        await queryRunner.query(`ALTER TABLE "application" ALTER COLUMN "applicationStatus" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "application" ALTER COLUMN "applicationStatus" TYPE "public"."ApplicationStatusEnum" USING "applicationStatus"::"text"::"public"."ApplicationStatusEnum"`);
        await queryRunner.query(`ALTER TABLE "application" ALTER COLUMN "applicationStatus" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."ApplicationStatusEnum_old"`);
        await queryRunner.query(`ALTER TABLE "financial_credit_report" ADD CONSTRAINT "FK_ba40ff1fe45e64512dc5e0f7bad" FOREIGN KEY ("supporting_document_id") REFERENCES "application_supporting_document"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD CONSTRAINT "FK_9b58b2c0b80ab60f17ae979684c" FOREIGN KEY ("application_id") REFERENCES "application"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_high_classification_scoring" ADD CONSTRAINT "FK_ea7e3eb20d8efeaf58ceda5caf1" FOREIGN KEY ("riskApplicationScoringId") REFERENCES "risk_application_scoring"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_high_classification_scoring" ADD CONSTRAINT "FK_60a7434cbe726112c5ee629a505" FOREIGN KEY ("riskHighClassificationFactorId") REFERENCES "risk_high_classification_factor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_high_classification_factor" ADD CONSTRAINT "FK_a8522a77d7788bbd799accd8efe" FOREIGN KEY ("riskModelId") REFERENCES "risk_model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_factor_scoring" ADD CONSTRAINT "FK_d0a4f694e87998756a93d6304a3" FOREIGN KEY ("riskApplicationScoringId") REFERENCES "risk_application_scoring"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_factor_scoring" ADD CONSTRAINT "FK_d3b01710b94d9f2889f89b381a5" FOREIGN KEY ("riskFactorId") REFERENCES "risk_factor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_factor_scoring" ADD CONSTRAINT "FK_becac4fd89c063fadfb51b5a16a" FOREIGN KEY ("selectedEvaluationParamId") REFERENCES "risk_evaluation_parameter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_factor_scoring" ADD CONSTRAINT "FK_c6793ae9b26304fa86c158d2cdb" FOREIGN KEY ("parentId") REFERENCES "risk_factor_scoring"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_evaluation_parameter" ADD CONSTRAINT "FK_7b5770c1c25d589669aa6b3aae0" FOREIGN KEY ("riskFactorId") REFERENCES "risk_factor"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_factor" ADD CONSTRAINT "FK_18c46a2c1e744982769d46f56b3" FOREIGN KEY ("riskModelId") REFERENCES "risk_model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_application_audit_log" ADD CONSTRAINT "FK_0ca389d89fbc02e7e309b74a338" FOREIGN KEY ("risk_application_scoring_id") REFERENCES "risk_application_scoring"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_manual_review_alert" ADD CONSTRAINT "FK_40106db61d1697dc341b7c10939" FOREIGN KEY ("risk_application_scoring_id") REFERENCES "risk_application_scoring"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_manual_review_alert" ADD CONSTRAINT "FK_4b1ec98c989eae5b88d6f664592" FOREIGN KEY ("quantitative_parameter_id") REFERENCES "risk_quantitative_parameter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_manual_review_alert" ADD CONSTRAINT "FK_8783a73d0484a7a591f1dfa183a" FOREIGN KEY ("quantitative_sub_parameter_id") REFERENCES "risk_quantitative_sub_parameter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_manual_review_alert" ADD CONSTRAINT "FK_a3b38e116e11854e6cb2927a3a8" FOREIGN KEY ("threshold_rule_id") REFERENCES "risk_quantitative_threshold_rule"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_application_scoring" ADD CONSTRAINT "FK_af2c45573a4e901a7cd84aa2350" FOREIGN KEY ("applicationId") REFERENCES "application"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_application_scoring" ADD CONSTRAINT "FK_afcb45086d6b2797733a744df58" FOREIGN KEY ("riskModelId") REFERENCES "risk_model"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_application_scoring" ADD CONSTRAINT "FK_076678869a19daf7eeafc7e6573" FOREIGN KEY ("risk_profile_id") REFERENCES "risk_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_profile_scoring" ADD CONSTRAINT "FK_24d374a66132d1c4de0cc066dfe" FOREIGN KEY ("risk_application_scoring_id") REFERENCES "risk_application_scoring"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_profile_scoring" ADD CONSTRAINT "FK_f7df1353b54e3392d845fa642d1" FOREIGN KEY ("quantitative_parameter_id") REFERENCES "risk_quantitative_parameter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_profile_scoring" ADD CONSTRAINT "FK_83fe0c14b5ae54b59f6e97ee24d" FOREIGN KEY ("quantitative_sub_parameter_id") REFERENCES "risk_quantitative_sub_parameter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_profile_scoring" ADD CONSTRAINT "FK_1a42b42383de908cc7fa9477d69" FOREIGN KEY ("threshold_rule_id") REFERENCES "risk_quantitative_threshold_rule"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_threshold_rule" ADD CONSTRAINT "FK_e5226c89ae404f4819c507e8eeb" FOREIGN KEY ("risk_profile_id") REFERENCES "risk_profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_threshold_rule" ADD CONSTRAINT "FK_b195b1686d55a5f5d5ed7cc0476" FOREIGN KEY ("quantitative_parameter_id") REFERENCES "risk_quantitative_parameter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_threshold_rule" ADD CONSTRAINT "FK_ec11dee1660199d05525312f894" FOREIGN KEY ("quantitative_sub_parameter_id") REFERENCES "risk_quantitative_sub_parameter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_profile_weight" ADD CONSTRAINT "FK_aa7714147eef547933208a5a625" FOREIGN KEY ("risk_profile_id") REFERENCES "risk_profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_profile_weight" ADD CONSTRAINT "FK_3a82d4ff9e958b6b5201c970b59" FOREIGN KEY ("quantitative_parameter_id") REFERENCES "risk_quantitative_parameter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_profile_weight" ADD CONSTRAINT "FK_33d984601402a2abdc87ec30e48" FOREIGN KEY ("quantitative_sub_parameter_id") REFERENCES "risk_quantitative_sub_parameter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_sub_parameter" ADD CONSTRAINT "FK_fcc298aa423158db84c7fe4c6c3" FOREIGN KEY ("quantitative_parameter_id") REFERENCES "risk_quantitative_parameter"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "risk_quantitative_sub_parameter" DROP CONSTRAINT "FK_fcc298aa423158db84c7fe4c6c3"`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_profile_weight" DROP CONSTRAINT "FK_33d984601402a2abdc87ec30e48"`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_profile_weight" DROP CONSTRAINT "FK_3a82d4ff9e958b6b5201c970b59"`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_profile_weight" DROP CONSTRAINT "FK_aa7714147eef547933208a5a625"`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_threshold_rule" DROP CONSTRAINT "FK_ec11dee1660199d05525312f894"`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_threshold_rule" DROP CONSTRAINT "FK_b195b1686d55a5f5d5ed7cc0476"`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_threshold_rule" DROP CONSTRAINT "FK_e5226c89ae404f4819c507e8eeb"`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_profile_scoring" DROP CONSTRAINT "FK_1a42b42383de908cc7fa9477d69"`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_profile_scoring" DROP CONSTRAINT "FK_83fe0c14b5ae54b59f6e97ee24d"`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_profile_scoring" DROP CONSTRAINT "FK_f7df1353b54e3392d845fa642d1"`);
        await queryRunner.query(`ALTER TABLE "risk_quantitative_profile_scoring" DROP CONSTRAINT "FK_24d374a66132d1c4de0cc066dfe"`);
        await queryRunner.query(`ALTER TABLE "risk_application_scoring" DROP CONSTRAINT "FK_076678869a19daf7eeafc7e6573"`);
        await queryRunner.query(`ALTER TABLE "risk_application_scoring" DROP CONSTRAINT "FK_afcb45086d6b2797733a744df58"`);
        await queryRunner.query(`ALTER TABLE "risk_application_scoring" DROP CONSTRAINT "FK_af2c45573a4e901a7cd84aa2350"`);
        await queryRunner.query(`ALTER TABLE "risk_manual_review_alert" DROP CONSTRAINT "FK_a3b38e116e11854e6cb2927a3a8"`);
        await queryRunner.query(`ALTER TABLE "risk_manual_review_alert" DROP CONSTRAINT "FK_8783a73d0484a7a591f1dfa183a"`);
        await queryRunner.query(`ALTER TABLE "risk_manual_review_alert" DROP CONSTRAINT "FK_4b1ec98c989eae5b88d6f664592"`);
        await queryRunner.query(`ALTER TABLE "risk_manual_review_alert" DROP CONSTRAINT "FK_40106db61d1697dc341b7c10939"`);
        await queryRunner.query(`ALTER TABLE "risk_application_audit_log" DROP CONSTRAINT "FK_0ca389d89fbc02e7e309b74a338"`);
        await queryRunner.query(`ALTER TABLE "risk_factor" DROP CONSTRAINT "FK_18c46a2c1e744982769d46f56b3"`);
        await queryRunner.query(`ALTER TABLE "risk_evaluation_parameter" DROP CONSTRAINT "FK_7b5770c1c25d589669aa6b3aae0"`);
        await queryRunner.query(`ALTER TABLE "risk_factor_scoring" DROP CONSTRAINT "FK_c6793ae9b26304fa86c158d2cdb"`);
        await queryRunner.query(`ALTER TABLE "risk_factor_scoring" DROP CONSTRAINT "FK_becac4fd89c063fadfb51b5a16a"`);
        await queryRunner.query(`ALTER TABLE "risk_factor_scoring" DROP CONSTRAINT "FK_d3b01710b94d9f2889f89b381a5"`);
        await queryRunner.query(`ALTER TABLE "risk_factor_scoring" DROP CONSTRAINT "FK_d0a4f694e87998756a93d6304a3"`);
        await queryRunner.query(`ALTER TABLE "risk_high_classification_factor" DROP CONSTRAINT "FK_a8522a77d7788bbd799accd8efe"`);
        await queryRunner.query(`ALTER TABLE "risk_high_classification_scoring" DROP CONSTRAINT "FK_60a7434cbe726112c5ee629a505"`);
        await queryRunner.query(`ALTER TABLE "risk_high_classification_scoring" DROP CONSTRAINT "FK_ea7e3eb20d8efeaf58ceda5caf1"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP CONSTRAINT "FK_9b58b2c0b80ab60f17ae979684c"`);
        await queryRunner.query(`ALTER TABLE "financial_credit_report" DROP CONSTRAINT "FK_ba40ff1fe45e64512dc5e0f7bad"`);
        await queryRunner.query(`CREATE TYPE "public"."ApplicationStatusEnum_old" AS ENUM('DRAFT', 'PENDING_EXPERIAN_CONSENT', 'PENDING_EXPERIAN_REPORT', 'PENDING_CLIENT_SUBMISSION', 'PENDING_ASSIGNEE_REVIEW', 'PENDING_RISK_REVIEW')`);
        await queryRunner.query(`ALTER TABLE "application" ALTER COLUMN "applicationStatus" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "application" ALTER COLUMN "applicationStatus" TYPE "public"."ApplicationStatusEnum_old" USING "applicationStatus"::"text"::"public"."ApplicationStatusEnum_old"`);
        await queryRunner.query(`ALTER TABLE "application" ALTER COLUMN "applicationStatus" SET DEFAULT 'DRAFT'`);
        await queryRunner.query(`DROP TYPE "public"."ApplicationStatusEnum"`);
        await queryRunner.query(`ALTER TYPE "public"."ApplicationStatusEnum_old" RENAME TO "ApplicationStatusEnum"`);
        await queryRunner.query(`ALTER TABLE "application" DROP CONSTRAINT "UQ_b1d358131fef2ce43b4176f3b06"`);
        await queryRunner.query(`ALTER TABLE "application" DROP COLUMN "applicationNumber"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "updated_at"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "is_active"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "is_verified"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "bucket_key"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "supporting_document_type"`);
        await queryRunner.query(`DROP TYPE "public"."ApplicationSupportingDocumentTypeEnum"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "file_extension"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "file_name"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" DROP COLUMN "application_id"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "isVerified" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "applicationId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT ('now'::text)::timestamp without time zone`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "isActive" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "fileExtension" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."ApplicationSupportingDocumentTypeEnum" AS ENUM('LETTER_OF_AWARD', 'PURCHASE_ORDER', 'CONTRACT', 'MISSING_PAGES', 'CASH_FLOW_APPENDED', 'APPENDIX_IN_CONTRACT', 'RELATED_COMPANY_NOTES', 'BANK_STATEMENT', 'FINANCIAL_STATEMENT', 'COMPANY_PROFILE', 'COMPANY_GROUP_STRUCTURE', 'ORGANIZATION_CHART', 'CREDIT_CONSENT_FORM', 'SITE_VISIT_REPORT')`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "supportingDocumentType" "public"."ApplicationSupportingDocumentTypeEnum"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD "bucketKey" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "risk_quantitative_parameter"`);
        await queryRunner.query(`DROP TABLE "risk_quantitative_sub_parameter"`);
        await queryRunner.query(`DROP TABLE "risk_quantitative_profile_weight"`);
        await queryRunner.query(`DROP TABLE "risk_profile"`);
        await queryRunner.query(`DROP TYPE "public"."BusinessSectorEnum"`);
        await queryRunner.query(`DROP TABLE "risk_quantitative_threshold_rule"`);
        await queryRunner.query(`DROP TYPE "public"."ThresholdBreachTriggerComparisonOperatorEnum"`);
        await queryRunner.query(`DROP TABLE "risk_quantitative_profile_scoring"`);
        await queryRunner.query(`DROP TABLE "risk_application_scoring"`);
        await queryRunner.query(`DROP TYPE "public"."RiskCategoryEnum_Filter2"`);
        await queryRunner.query(`DROP TYPE "public"."RiskFilter1StatusEnum"`);
        await queryRunner.query(`DROP TYPE "public"."RiskCategoryEnum_Filter1"`);
        await queryRunner.query(`DROP TABLE "risk_manual_review_alert"`);
        await queryRunner.query(`DROP TABLE "risk_application_audit_log"`);
        await queryRunner.query(`DROP TYPE "public"."RiskApplicationAuditActionEnum"`);
        await queryRunner.query(`DROP TABLE "risk_model"`);
        await queryRunner.query(`DROP TYPE "public"."RiskModelStatusEnum"`);
        await queryRunner.query(`DROP TABLE "risk_factor"`);
        await queryRunner.query(`DROP TYPE "public"."RiskFactorScoreMethodEnum"`);
        await queryRunner.query(`DROP TABLE "risk_evaluation_parameter"`);
        await queryRunner.query(`DROP TYPE "public"."RiskEvalScoreTypeEnum"`);
        await queryRunner.query(`DROP TYPE "public"."RiskCategoryEnum_RiskEvaluationParam"`);
        await queryRunner.query(`DROP TABLE "risk_factor_scoring"`);
        await queryRunner.query(`DROP TABLE "risk_high_classification_factor"`);
        await queryRunner.query(`DROP TABLE "risk_high_classification_scoring"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_80c1401c52215af0630e72091c"`);
        await queryRunner.query(`DROP TABLE "financial_credit_report"`);
        await queryRunner.query(`DROP TYPE "public"."FinancialCreditReportTypeEnum"`);
        await queryRunner.query(`ALTER TABLE "application_supporting_document" ADD CONSTRAINT "FK_20c4be58213e8af3ba5b2ad49e0" FOREIGN KEY ("applicationId") REFERENCES "application"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
